#ifndef _FW_MMAP_H_
#define _FW_MMAP_H_

//This file is auto generated, do no edit
//Update wlanfw_mmap.cfg file instead
//Some of the comments are also copied from original file

#define	QWLANFW_MEMINFO_START_ADDR		(0x50)//
#define	QWLANFW_MEMINFO_SIZE		(0xC8)// 0x50 - 0x118
#define	QWLANFW_MEMMAP_START_ADDR		(0x500)//
#define	QWLANFW_MEM_H2F_MSG_SIZE		(0x100)// 0x500 - 0x600
#define	QWLANFW_MEM_F2H_MSG_SIZE		(0x100)// 0x600 - 0x700
#define	QWLANFW_MEM_FW_LOG_SIZE		(0xC00)// 0x700 - 0x1300
#define	QWLANFW_MEM_ERR_STATS_SIZE		(0x80)// 0x1300 - 0x1380
#define	QWLANFW_MEM_PHY_CAL_CONTROL_BITMAP_SIZE		(0x04)// 0x1380 - 0x1384
#define	QWLANFW_MEM_PHY_CAL_STATUS_SIZE		(0x20)// 0x1384 - 0x13A4
#define	QWLANFW_MEM_PHY_CAL_CORRECTIONS_SIZE		(0x1150)// 0x13A4 - 0x24F4
#define	QWLANFW_MEM_HW_COUNTERS_SIZE		(0x100)// 0x24F4 - 0x25F4
#define	QWLANFW_MEM_SYS_CONFIG_SIZE		(0x100)// 0x25F4 - 0x26F4
#define	QWLANFW_MEM_FW_PS_COUNTERS_SIZE		(0xAC)// 0x26F4 - 0x27A0 
#define	QWLANFW_MEM_PHY_FTM_INFO_SIZE		(0x10)// 0x27A0 - 0x27B0 
// Calculate address from the start address and size
#define	QWLANFW_MEM_H2F_MSG_ADDR_OFFSET		(QWLANFW_MEMMAP_START_ADDR)//
#define	QWLANFW_MEM_F2H_MSG_ADDR_OFFSET		(QWLANFW_MEM_H2F_MSG_ADDR_OFFSET+QWLANFW_MEM_H2F_MSG_SIZE)//
#define	QWLANFW_MEM_FW_LOG_ADDR_OFFSET		(QWLANFW_MEM_F2H_MSG_ADDR_OFFSET+QWLANFW_MEM_F2H_MSG_SIZE)//
#define	QWLANFW_MEM_ERR_STATS_ADDR_OFFSET		(QWLANFW_MEM_FW_LOG_ADDR_OFFSET+QWLANFW_MEM_FW_LOG_SIZE)//
#define	QWLANFW_MEM_PHY_CAL_CONTROL_BITMAP_ADDR_OFFSET		(QWLANFW_MEM_ERR_STATS_ADDR_OFFSET+QWLANFW_MEM_ERR_STATS_SIZE)//
#define	QWLANFW_MEM_PHY_CAL_STATUS_ADDR_OFFSET		(QWLANFW_MEM_PHY_CAL_CONTROL_BITMAP_ADDR_OFFSET+QWLANFW_MEM_PHY_CAL_CONTROL_BITMAP_SIZE)//
#define	QWLANFW_MEM_PHY_CAL_CORRECTIONS_ADDR_OFFSET		(QWLANFW_MEM_PHY_CAL_STATUS_ADDR_OFFSET+QWLANFW_MEM_PHY_CAL_STATUS_SIZE)//
#define	QWLANFW_MEM_HW_COUNTERS_ADDR_OFFSET		(QWLANFW_MEM_PHY_CAL_CORRECTIONS_ADDR_OFFSET+QWLANFW_MEM_PHY_CAL_CORRECTIONS_SIZE)//
#define	QWLANFW_MEM_SYS_CONFIG_ADDR_OFFSET		(QWLANFW_MEM_HW_COUNTERS_ADDR_OFFSET+QWLANFW_MEM_HW_COUNTERS_SIZE)//
#define	QWLANFW_MEM_FW_PS_COUNTERS_ADDR_OFFSET		(QWLANFW_MEM_SYS_CONFIG_ADDR_OFFSET+QWLANFW_MEM_SYS_CONFIG_SIZE)//
#define	QWLANFW_MEM_PHY_FTM_INFO_ADDR_OFFSET		(QWLANFW_MEM_FW_PS_COUNTERS_ADDR_OFFSET+QWLANFW_MEM_FW_PS_COUNTERS_SIZE)//
#define	QWLANFW_MEMMAP_RA_SHARED_TABLE_ADDR		(QWLANFW_MEM_PHY_FTM_INFO_ADDR_OFFSET+QWLANFW_MEM_PHY_FTM_INFO_SIZE)//



#endif /*_FW_MMAP_H_*/
