#!/bin/sh

deltadir="/tmp"
bindir="/tmp"

/bin/mkdir -p $deltadir

deltafile="$deltadir/cfg.delta"
tmpdeltafile="$deltadir/cfg.delta.tmp"

usage="radioDiag [config_name config_val]"

#main starts here
case "$#" in
0)
    	if [ -f $deltafile ]
    	then
		if [ -s $deltafile ]
		then
    			/bin/cat $deltafile
		else
  			/bin/echo "No Entries found"
		fi
  	else
  		/bin/echo "No Entries found"
  	fi
	;;
2)
	if [ $1 = "-d" ]
	then
		if [ -f $deltafile ]
		then
			/bin/sed "/$2/d" $deltafile > $tmpdeltafile
			if [ $? -eq 0 ]
			then
				/bin/cat $tmpdeltafile > $deltafile
				/bin/rm $tmpdeltafile

				/diags/updateCfg > /dev/null 2>&1
				/usr/sbin/aniCfgGen -b -s /tmp -d /tmp > /dev/null 2>&1

				/bin/echo "Issue Commit Global Settings for changes to take effect"
			fi
		fi
	else
		if [ -f $deltafile ]
		then
			/bin/sed "/$1/d" $deltafile > $tmpdeltafile
			if [ $? -eq 0 ]
			then
				/bin/cat $tmpdeltafile > $deltafile
				/bin/rm $tmpdeltafile
			fi
		fi
		/bin/echo "$1		$2" >> $deltafile

		$bindir/updateCfg > /dev/null 2>&1
		$bindir/aniCfgGen -b -s /tmp -d /tmp > /dev/null 2>&1

		/bin/echo "Issue Commit Global Settings for changes to take effect"
	fi
	;;
*)
	/bin/echo $usage
	;;
		 
esac

exit

