/** ************************************************************************
 * quasar.h: QUASAR module header file. This file is auto generated from
 *           quasar.reg file. If changes are made in this file, they 
 *           they will be written over when reg2h.pl script is executed on
 *           quasar.reg file.

 * Date:Wed Aug 23 11:31:14 2006
 * Copy Right: Airgo Networks, INC., PALO ALTO, CA, USA
 * 
 * -------------------------------------------------------------------------
 */

#ifndef QUASAR_H
#define QUASAR_H


#define QUASAR_BASE	0x00000000

// ------------------------------------------------------------------- 
#define QUASAR_PLL1_REG	QUASAR_BASE + 0x0

#define QUASAR_PLL1_NDIV_INT_MASK	0x3F800
#define QUASAR_PLL1_NDIV_INT_OFFSET	0xB
#define QUASAR_PLL1_NDIV_INT_DEFAULT	0x28000

#define QUASAR_PLL1_NDIV_FRAC_MASK	0x600
#define QUASAR_PLL1_NDIV_FRAC_OFFSET	0x9
#define QUASAR_PLL1_NDIV_FRAC_DEFAULT	0x200

#define QUASAR_PLL1_CP_GAIN_MASK	0x1F0
#define QUASAR_PLL1_CP_GAIN_OFFSET	0x4
#define QUASAR_PLL1_CP_GAIN_DEFAULT	0x100
#define QUASAR_PLL1_CP_GAIN_EONF	0x0
#define QUASAR_PLL1_CP_GAIN_EONH	0x1
#define QUASAR_PLL1_CP_GAIN_ETWF	0x2
#define QUASAR_PLL1_CP_GAIN_ETWH	0x2
#define QUASAR_PLL1_CP_GAIN_ESXT	0x1F

#define QUASAR_PLL1_NDIV_EN_MASK	0x8
#define QUASAR_PLL1_NDIV_EN_OFFSET	0x3
#define QUASAR_PLL1_NDIV_EN_DEFAULT	0x8

#define QUASAR_PLL1_PFD_EN_MASK	0x4
#define QUASAR_PLL1_PFD_EN_OFFSET	0x2
#define QUASAR_PLL1_PFD_EN_DEFAULT	0x4

#define QUASAR_PLL1_CP_EN_MASK	0x2
#define QUASAR_PLL1_CP_EN_OFFSET	0x1
#define QUASAR_PLL1_CP_EN_DEFAULT	0x2

#define QUASAR_PLL1_FNZ_MASK	0x1
#define QUASAR_PLL1_FNZ_OFFSET	0x0
#define QUASAR_PLL1_FNZ_DEFAULT	0x0
#define QUASAR_PLL1_DEFAULT		0x2830E

// ------------------------------------------------------------------- 
#define QUASAR_PLL2_REG	QUASAR_BASE + 0x1

#define QUASAR_PLL2_NDIV_FRAC_MASK	0x3FFFF
#define QUASAR_PLL2_NDIV_FRAC_OFFSET	0x0
#define QUASAR_PLL2_NDIV_FRAC_DEFAULT	0x26666
#define QUASAR_PLL2_DEFAULT		0x26666

// ------------------------------------------------------------------- 
#define QUASAR_PLL3_REG	QUASAR_BASE + 0x2

#define QUASAR_PLL3_PLL_CT_ACTIVE_MASK	0x20000
#define QUASAR_PLL3_PLL_CT_ACTIVE_OFFSET	0x11
#define QUASAR_PLL3_PLL_CT_ACTIVE_DEFAULT	0x0

#define QUASAR_PLL3_VCO_EN_MASK	0x18000
#define QUASAR_PLL3_VCO_EN_OFFSET	0xF
#define QUASAR_PLL3_VCO_EN_DEFAULT	0x0
#define QUASAR_PLL3_VCO_EN_EAUTOMATIC	0x0
#define QUASAR_PLL3_VCO_EN_ELOW	0x1
#define QUASAR_PLL3_VCO_EN_EHIGH	0x2
#define QUASAR_PLL3_VCO_EN_EOFF	0x3

#define QUASAR_PLL3_CT_EN_MASK	0x4000
#define QUASAR_PLL3_CT_EN_OFFSET	0xE
#define QUASAR_PLL3_CT_EN_DEFAULT	0x4000
#define QUASAR_PLL3_CT_EN_EMANUAL	0x0
#define QUASAR_PLL3_CT_EN_EAUTOMATIC	0x1

#define QUASAR_PLL3_RDIV_MASK	0x3000
#define QUASAR_PLL3_RDIV_OFFSET	0xC
#define QUASAR_PLL3_RDIV_DEFAULT	0x2000
#define QUASAR_PLL3_RDIV_E80MHZ	0x0
#define QUASAR_PLL3_RDIV_E53MHZ	0x1
#define QUASAR_PLL3_RDIV_E40MHZ	0x2
#define QUASAR_PLL3_RDIV_E27MHZ	0x3

#define QUASAR_PLL3_EXT_RFLO_EN_MASK	0x800
#define QUASAR_PLL3_EXT_RFLO_EN_OFFSET	0xB
#define QUASAR_PLL3_EXT_RFLO_EN_DEFAULT	0x0

#define QUASAR_PLL3_RFLO_OUT_EN_MASK	0x400
#define QUASAR_PLL3_RFLO_OUT_EN_OFFSET	0xA
#define QUASAR_PLL3_RFLO_OUT_EN_DEFAULT	0x0

#define QUASAR_PLL3_PLL_CT_START_MASK	0x200
#define QUASAR_PLL3_PLL_CT_START_OFFSET	0x9
#define QUASAR_PLL3_PLL_CT_START_DEFAULT	0x0

#define QUASAR_PLL3_PLL_ADC_AQ_MASK	0x100
#define QUASAR_PLL3_PLL_ADC_AQ_OFFSET	0x8
#define QUASAR_PLL3_PLL_ADC_AQ_DEFAULT	0x0

#define QUASAR_PLL3_VTUNE_VAL_MASK	0xF8
#define QUASAR_PLL3_VTUNE_VAL_OFFSET	0x3
#define QUASAR_PLL3_VTUNE_VAL_DEFAULT	0x0

#define QUASAR_PLL3_CT_MAINT_MASK	0x7
#define QUASAR_PLL3_CT_MAINT_OFFSET	0x0
#define QUASAR_PLL3_CT_MAINT_DEFAULT	0x0
#define QUASAR_PLL3_CT_MAINT_EDISABLED	0x0
#define QUASAR_PLL3_CT_MAINT_EONCE	0x1
#define QUASAR_PLL3_CT_MAINT_E1MIN	0x2
#define QUASAR_PLL3_CT_MAINT_E2MIN	0x4
#define QUASAR_PLL3_CT_MAINT_E5MIN	0x6
#define QUASAR_PLL3_DEFAULT		0x6000

// ------------------------------------------------------------------- 
#define QUASAR_PLL4_REG	QUASAR_BASE + 0x3

#define QUASAR_PLL4_PLL_TUNE_ERR_MASK	0x20000
#define QUASAR_PLL4_PLL_TUNE_ERR_OFFSET	0x11
#define QUASAR_PLL4_PLL_TUNE_ERR_DEFAULT	0x0

#define QUASAR_PLL4_PLL_VREG_D_MASK	0x10000
#define QUASAR_PLL4_PLL_VREG_D_OFFSET	0x10
#define QUASAR_PLL4_PLL_VREG_D_DEFAULT	0x0
#define QUASAR_PLL4_PLL_VREG_D_E250US	0x0
#define QUASAR_PLL4_PLL_VREG_D_E500US	0x1

#define QUASAR_PLL4_PLL_VREG_EN_MASK	0x8000
#define QUASAR_PLL4_PLL_VREG_EN_OFFSET	0xF
#define QUASAR_PLL4_PLL_VREG_EN_DEFAULT	0x8000
#define QUASAR_PLL4_PLL_VREG_EN_EOFF	0x0
#define QUASAR_PLL4_PLL_VREG_EN_EENABLED	0x1

#define QUASAR_PLL4_VCO_VREG_EN_MASK	0x4000
#define QUASAR_PLL4_VCO_VREG_EN_OFFSET	0xE
#define QUASAR_PLL4_VCO_VREG_EN_DEFAULT	0x4000
#define QUASAR_PLL4_VCO_VREG_EN_EOFF	0x0
#define QUASAR_PLL4_VCO_VREG_EN_EEN	0x1

#define QUASAR_PLL4_VTUNE_RANGE_MASK	0x3000
#define QUASAR_PLL4_VTUNE_RANGE_OFFSET	0xC
#define QUASAR_PLL4_VTUNE_RANGE_DEFAULT	0x0
#define QUASAR_PLL4_VTUNE_RANGE_E9_LSBS	0x0
#define QUASAR_PLL4_VTUNE_RANGE_E8_LSBS	0x1
#define QUASAR_PLL4_VTUNE_RANGE_E10_LSBS	0x2
#define QUASAR_PLL4_VTUNE_RANGE_E14_LSBS	0x3

#define QUASAR_PLL4_CT_VAL_MASK	0xFE0
#define QUASAR_PLL4_CT_VAL_OFFSET	0x5
#define QUASAR_PLL4_CT_VAL_DEFAULT	0x400

#define QUASAR_PLL4_VTUNE_T_MASK	0x1F
#define QUASAR_PLL4_VTUNE_T_OFFSET	0x0
#define QUASAR_PLL4_VTUNE_T_DEFAULT	0x12
#define QUASAR_PLL4_DEFAULT		0xC412

// ------------------------------------------------------------------- 
#define QUASAR_PLL5_REG	QUASAR_BASE + 0x4

#define QUASAR_PLL5_VCO_SEL_MASK	0x20000
#define QUASAR_PLL5_VCO_SEL_OFFSET	0x11
#define QUASAR_PLL5_VCO_SEL_DEFAULT	0x0
#define QUASAR_PLL5_VCO_SEL_ELOW	0x0
#define QUASAR_PLL5_VCO_SEL_EHIGH	0x1

#define QUASAR_PLL5_CT_SETIME_MASK	0x10000
#define QUASAR_PLL5_CT_SETIME_OFFSET	0x10
#define QUASAR_PLL5_CT_SETIME_DEFAULT	0x0
#define QUASAR_PLL5_CT_SETIME_E65US	0x0
#define QUASAR_PLL5_CT_SETIME_E50US	0x1

#define QUASAR_PLL5_THREE_FOURB_MASK	0x8000
#define QUASAR_PLL5_THREE_FOURB_OFFSET	0xF
#define QUASAR_PLL5_THREE_FOURB_DEFAULT	0x0
#define QUASAR_PLL5_THREE_FOURB_E3RD_ORDER	0x0
#define QUASAR_PLL5_THREE_FOURB_E4TH_ORDER	0x1

#define QUASAR_PLL5_IBUF_BIAS_MASK	0x7000
#define QUASAR_PLL5_IBUF_BIAS_OFFSET	0xC
#define QUASAR_PLL5_IBUF_BIAS_DEFAULT	0x4000
#define QUASAR_PLL5_IBUF_BIAS_E1P8_MA	0x0
#define QUASAR_PLL5_IBUF_BIAS_E2P0_MA	0x1
#define QUASAR_PLL5_IBUF_BIAS_E2P2_MA	0x2
#define QUASAR_PLL5_IBUF_BIAS_E2P4_MA	0x3
#define QUASAR_PLL5_IBUF_BIAS_E2P6_MA	0x4
#define QUASAR_PLL5_IBUF_BIAS_E2P8_MA	0x5
#define QUASAR_PLL5_IBUF_BIAS_E3P0_MA	0x6

#define QUASAR_PLL5_VCO_BIAS_MASK	0xE00
#define QUASAR_PLL5_VCO_BIAS_OFFSET	0x9
#define QUASAR_PLL5_VCO_BIAS_DEFAULT	0x800
#define QUASAR_PLL5_VCO_BIAS_E6P5_MA	0x0
#define QUASAR_PLL5_VCO_BIAS_E7P0_MA	0x1
#define QUASAR_PLL5_VCO_BIAS_E7P5_MA	0x2
#define QUASAR_PLL5_VCO_BIAS_E7P9_MA	0x3
#define QUASAR_PLL5_VCO_BIAS_E8P4_MA	0x4
#define QUASAR_PLL5_VCO_BIAS_E8P8_MA	0x5
#define QUASAR_PLL5_VCO_BIAS_E9P2_MA	0x6
#define QUASAR_PLL5_VCO_BIAS_E9P7_MA	0x7

#define QUASAR_PLL5_CP_LOGIC_MASK	0x1C0
#define QUASAR_PLL5_CP_LOGIC_OFFSET	0x6
#define QUASAR_PLL5_CP_LOGIC_DEFAULT	0x0
#define QUASAR_PLL5_CP_LOGIC_EBACKLASH_NOMINAL	0x0
#define QUASAR_PLL5_CP_LOGIC_EBOTH_CP_OFF	0x1
#define QUASAR_PLL5_CP_LOGIC_EBACKLASH_LONG	0x2
#define QUASAR_PLL5_CP_LOGIC_EUP_CP_ON	0x3
#define QUASAR_PLL5_CP_LOGIC_EBACKLASH_SHORT	0x4
#define QUASAR_PLL5_CP_LOGIC_EDOWN_CP_ON	0x5
#define QUASAR_PLL5_CP_LOGIC_EPHASE_DET_RESET	0x6
#define QUASAR_PLL5_CP_LOGIC_EBOTH_CP_ON	0x7

#define QUASAR_PLL5_FRAC_OFFS_MASK	0x3C
#define QUASAR_PLL5_FRAC_OFFS_OFFSET	0x2
#define QUASAR_PLL5_FRAC_OFFS_DEFAULT	0x28

#define QUASAR_PLL5_NDIV_BIAS_MASK	0x3
#define QUASAR_PLL5_NDIV_BIAS_OFFSET	0x0
#define QUASAR_PLL5_NDIV_BIAS_DEFAULT	0x1
#define QUASAR_PLL5_NDIV_BIAS_EMINUS_20_PCT	0x0
#define QUASAR_PLL5_NDIV_BIAS_ENOMINAL	0x1
#define QUASAR_PLL5_NDIV_BIAS_EPLUS_20_PCT	0x2
#define QUASAR_PLL5_NDIV_BIAS_EPLUS_40_PCT	0x3
#define QUASAR_PLL5_DEFAULT		0x4829

// ------------------------------------------------------------------- 
#define QUASAR_PLL6_REG	QUASAR_BASE + 0x5

#define QUASAR_PLL6_LBW_CAL_SU_MASK	0x20000
#define QUASAR_PLL6_LBW_CAL_SU_OFFSET	0x11
#define QUASAR_PLL6_LBW_CAL_SU_DEFAULT	0x0
#define QUASAR_PLL6_LBW_CAL_SU_EPLL_EN_OR_CHAN_CHANGE	0x0
#define QUASAR_PLL6_LBW_CAL_SU_EPLL_EN_ONLY	0x1

#define QUASAR_PLL6_CP_GAIN_CAL_MASK	0x1F000
#define QUASAR_PLL6_CP_GAIN_CAL_OFFSET	0xC
#define QUASAR_PLL6_CP_GAIN_CAL_DEFAULT	0x0

#define QUASAR_PLL6_DELTA_NDIV_MASK	0xC00
#define QUASAR_PLL6_DELTA_NDIV_OFFSET	0xA
#define QUASAR_PLL6_DELTA_NDIV_DEFAULT	0x0
#define QUASAR_PLL6_DELTA_NDIV_E0P05	0x0
#define QUASAR_PLL6_DELTA_NDIV_E0P1	0x1
#define QUASAR_PLL6_DELTA_NDIV_E0P15	0x2
#define QUASAR_PLL6_DELTA_NDIV_E0P2	0x3

#define QUASAR_PLL6_PLL_TRANGE_MASK	0x380
#define QUASAR_PLL6_PLL_TRANGE_OFFSET	0x7
#define QUASAR_PLL6_PLL_TRANGE_DEFAULT	0x280

#define QUASAR_PLL6_PLL_TGOAL_MASK	0x7E
#define QUASAR_PLL6_PLL_TGOAL_OFFSET	0x1
#define QUASAR_PLL6_PLL_TGOAL_DEFAULT	0x38

#define QUASAR_PLL6_LOOP_CAL_EN_MASK	0x1
#define QUASAR_PLL6_LOOP_CAL_EN_OFFSET	0x0
#define QUASAR_PLL6_LOOP_CAL_EN_DEFAULT	0x0
#define QUASAR_PLL6_DEFAULT		0x2B8

// ------------------------------------------------------------------- 
#define QUASAR_LO_CONFIG_REG	QUASAR_BASE + 0x6

#define QUASAR_LO_CONFIG_RSVD_MASK	0x30000
#define QUASAR_LO_CONFIG_RSVD_OFFSET	0x10
#define QUASAR_LO_CONFIG_RSVD_DEFAULT	0x0

#define QUASAR_LO_CONFIG_EXT_IFLO_EN_MASK	0x8000
#define QUASAR_LO_CONFIG_EXT_IFLO_EN_OFFSET	0xF
#define QUASAR_LO_CONFIG_EXT_IFLO_EN_DEFAULT	0x0

#define QUASAR_LO_CONFIG_IQ_DIV_EN_MASK	0x4000
#define QUASAR_LO_CONFIG_IQ_DIV_EN_OFFSET	0xE
#define QUASAR_LO_CONFIG_IQ_DIV_EN_DEFAULT	0x4000

#define QUASAR_LO_CONFIG_NDIV_LO_MASK	0x3000
#define QUASAR_LO_CONFIG_NDIV_LO_OFFSET	0xC
#define QUASAR_LO_CONFIG_NDIV_LO_DEFAULT	0x0
#define QUASAR_LO_CONFIG_NDIV_LO_EDISABLE	0x0
#define QUASAR_LO_CONFIG_NDIV_LO_ELOW	0x1
#define QUASAR_LO_CONFIG_NDIV_LO_EMED	0x2
#define QUASAR_LO_CONFIG_NDIV_LO_EHI	0x3

#define QUASAR_LO_CONFIG_EXT_LO_MASK	0xC00
#define QUASAR_LO_CONFIG_EXT_LO_OFFSET	0xA
#define QUASAR_LO_CONFIG_EXT_LO_DEFAULT	0x0
#define QUASAR_LO_CONFIG_EXT_LO_EDISABLE	0x0
#define QUASAR_LO_CONFIG_EXT_LO_ELOW	0x1
#define QUASAR_LO_CONFIG_EXT_LO_EMED	0x2
#define QUASAR_LO_CONFIG_EXT_LO_EHI	0x3

#define QUASAR_LO_CONFIG_TX1_LO_MASK	0x300
#define QUASAR_LO_CONFIG_TX1_LO_OFFSET	0x8
#define QUASAR_LO_CONFIG_TX1_LO_DEFAULT	0x200
#define QUASAR_LO_CONFIG_TX1_LO_EDISABLE	0x0
#define QUASAR_LO_CONFIG_TX1_LO_ELOW	0x1
#define QUASAR_LO_CONFIG_TX1_LO_EMED	0x2
#define QUASAR_LO_CONFIG_TX1_LO_EHI	0x3

#define QUASAR_LO_CONFIG_TX0_LO_MASK	0xC0
#define QUASAR_LO_CONFIG_TX0_LO_OFFSET	0x6
#define QUASAR_LO_CONFIG_TX0_LO_DEFAULT	0x80
#define QUASAR_LO_CONFIG_TX0_LO_EDISABLE	0x0
#define QUASAR_LO_CONFIG_TX0_LO_ELOW	0x1
#define QUASAR_LO_CONFIG_TX0_LO_EMED	0x2
#define QUASAR_LO_CONFIG_TX0_LO_EHI	0x3

#define QUASAR_LO_CONFIG_RX2_LO_MASK	0x30
#define QUASAR_LO_CONFIG_RX2_LO_OFFSET	0x4
#define QUASAR_LO_CONFIG_RX2_LO_DEFAULT	0x20
#define QUASAR_LO_CONFIG_RX2_LO_EDISABLE	0x0
#define QUASAR_LO_CONFIG_RX2_LO_ELOW	0x1
#define QUASAR_LO_CONFIG_RX2_LO_EMED	0x2
#define QUASAR_LO_CONFIG_RX2_LO_EHI	0x3

#define QUASAR_LO_CONFIG_RX1_LO_MASK	0xC
#define QUASAR_LO_CONFIG_RX1_LO_OFFSET	0x2
#define QUASAR_LO_CONFIG_RX1_LO_DEFAULT	0x8
#define QUASAR_LO_CONFIG_RX1_LO_EDISABLE	0x0
#define QUASAR_LO_CONFIG_RX1_LO_ELOW	0x1
#define QUASAR_LO_CONFIG_RX1_LO_EMED	0x2
#define QUASAR_LO_CONFIG_RX1_LO_EHI	0x3

#define QUASAR_LO_CONFIG_RX0_LO_MASK	0x3
#define QUASAR_LO_CONFIG_RX0_LO_OFFSET	0x0
#define QUASAR_LO_CONFIG_RX0_LO_DEFAULT	0x2
#define QUASAR_LO_CONFIG_RX0_LO_EDISABLE	0x0
#define QUASAR_LO_CONFIG_RX0_LO_ELOW	0x1
#define QUASAR_LO_CONFIG_RX0_LO_EMED	0x2
#define QUASAR_LO_CONFIG_RX0_LO_EHI	0x3
#define QUASAR_LO_CONFIG_DEFAULT		0x42AA

// ------------------------------------------------------------------- 
#define QUASAR_STATE_REG	QUASAR_BASE + 0x7

#define QUASAR_STATE_MS_REV_MASK	0x30000
#define QUASAR_STATE_MS_REV_OFFSET	0x10
#define QUASAR_STATE_MS_REV_DEFAULT	0x0

#define QUASAR_STATE_XO_DISABLE_ST_MASK	0xC000
#define QUASAR_STATE_XO_DISABLE_ST_OFFSET	0xE
#define QUASAR_STATE_XO_DISABLE_ST_DEFAULT	0x0
#define QUASAR_STATE_XO_DISABLE_ST_EALL_OFF	0x0
#define QUASAR_STATE_XO_DISABLE_ST_EXO_ON	0x1
#define QUASAR_STATE_XO_DISABLE_ST_EXO_PLL_ON	0x2
#define QUASAR_STATE_XO_DISABLE_ST_EPLL_ON	0x3

#define QUASAR_STATE_RX1_ST_EN_MASK	0x3800
#define QUASAR_STATE_RX1_ST_EN_OFFSET	0xB
#define QUASAR_STATE_RX1_ST_EN_DEFAULT	0x800
#define QUASAR_STATE_RX1_ST_EN_EDISABLED	0x0
#define QUASAR_STATE_RX1_ST_EN_ERX0_EN	0x1
#define QUASAR_STATE_RX1_ST_EN_ERX1_EN	0xA
#define QUASAR_STATE_RX1_ST_EN_ERX0_RX1_EN	0xB
#define QUASAR_STATE_RX1_ST_EN_ERX2_EN	0x64
#define QUASAR_STATE_RX1_ST_EN_ERX2_RX0_EN	0x65
#define QUASAR_STATE_RX1_ST_EN_ERX2_RX1_EN	0x6E
#define QUASAR_STATE_RX1_ST_EN_EALL_EN	0x6F

#define QUASAR_STATE_RX_ALL_ST_EN_MASK	0x700
#define QUASAR_STATE_RX_ALL_ST_EN_OFFSET	0x8
#define QUASAR_STATE_RX_ALL_ST_EN_DEFAULT	0x700
#define QUASAR_STATE_RX_ALL_ST_EN_EDISABLED	0x0
#define QUASAR_STATE_RX_ALL_ST_EN_ERX0_EN	0x1
#define QUASAR_STATE_RX_ALL_ST_EN_ERX1_EN	0xA
#define QUASAR_STATE_RX_ALL_ST_EN_ERX0_RX1_EN	0xB
#define QUASAR_STATE_RX_ALL_ST_EN_ERX2_EN	0x64
#define QUASAR_STATE_RX_ALL_ST_EN_ERX2_RX0_EN	0x65
#define QUASAR_STATE_RX_ALL_ST_EN_ERX2_RX1_EN	0x6E
#define QUASAR_STATE_RX_ALL_ST_EN_EALL_EN	0x6F

#define QUASAR_STATE_TX_ST_EN_MASK	0xC0
#define QUASAR_STATE_TX_ST_EN_OFFSET	0x6
#define QUASAR_STATE_TX_ST_EN_DEFAULT	0xC0
#define QUASAR_STATE_TX_ST_EN_EDISABLED	0x0
#define QUASAR_STATE_TX_ST_EN_ETX0_EN	0x1
#define QUASAR_STATE_TX_ST_EN_ETX1_EN	0xA
#define QUASAR_STATE_TX_ST_EN_EALL_EN	0xB

#define QUASAR_STATE_PLL_EN_MASK	0x20
#define QUASAR_STATE_PLL_EN_OFFSET	0x5
#define QUASAR_STATE_PLL_EN_DEFAULT	0x0

#define QUASAR_STATE_TXRX_BAND_MASK	0x10
#define QUASAR_STATE_TXRX_BAND_OFFSET	0x4
#define QUASAR_STATE_TXRX_BAND_DEFAULT	0x0
#define QUASAR_STATE_TXRX_BAND_E2P4_GHZ	0x0
#define QUASAR_STATE_TXRX_BAND_E5_GHZ	0x1

#define QUASAR_STATE_MREV_MASK	0xE
#define QUASAR_STATE_MREV_OFFSET	0x1
#define QUASAR_STATE_MREV_DEFAULT	0x0

#define QUASAR_STATE_TWOG_HS_EN_MASK	0x1
#define QUASAR_STATE_TWOG_HS_EN_OFFSET	0x0
#define QUASAR_STATE_TWOG_HS_EN_DEFAULT	0x1
#define QUASAR_STATE_TWOG_HS_EN_ELOW_SIDE	0x0
#define QUASAR_STATE_TWOG_HS_EN_EHIGH_SIDE	0x1
#define QUASAR_STATE_DEFAULT		0xFC1

// ------------------------------------------------------------------- 
#define QUASAR_GC1_REG	QUASAR_BASE + 0x8

#define QUASAR_GC1_RXG_2_MASK	0x3F000
#define QUASAR_GC1_RXG_2_OFFSET	0xC
#define QUASAR_GC1_RXG_2_DEFAULT	0x0

#define QUASAR_GC1_RXG_1_MASK	0xFC0
#define QUASAR_GC1_RXG_1_OFFSET	0x6
#define QUASAR_GC1_RXG_1_DEFAULT	0x0

#define QUASAR_GC1_RXG_0_MASK	0x3F
#define QUASAR_GC1_RXG_0_OFFSET	0x0
#define QUASAR_GC1_RXG_0_DEFAULT	0x0
#define QUASAR_GC1_DEFAULT		0x0

// ------------------------------------------------------------------- 
#define QUASAR_GC2_REG	QUASAR_BASE + 0x9

#define QUASAR_GC2_RSVD_MASK	0x30000
#define QUASAR_GC2_RSVD_OFFSET	0x10
#define QUASAR_GC2_RSVD_DEFAULT	0x0

#define QUASAR_GC2_GC_SELECT_MASK	0x8000
#define QUASAR_GC2_GC_SELECT_OFFSET	0xF
#define QUASAR_GC2_GC_SELECT_DEFAULT	0x0
#define QUASAR_GC2_GC_SELECT_ERX	0x0
#define QUASAR_GC2_GC_SELECT_ETX	0x1

#define QUASAR_GC2_SPI_LUT_EN_MASK	0x4000
#define QUASAR_GC2_SPI_LUT_EN_OFFSET	0xE
#define QUASAR_GC2_SPI_LUT_EN_DEFAULT	0x0
#define QUASAR_GC2_SPI_LUT_EN_EGC	0x0
#define QUASAR_GC2_SPI_LUT_EN_ESPI	0x1

#define QUASAR_GC2_SPI_LUT_INDEX_MASK	0x3F00
#define QUASAR_GC2_SPI_LUT_INDEX_OFFSET	0x8
#define QUASAR_GC2_SPI_LUT_INDEX_DEFAULT	0x0

#define QUASAR_GC2_TX_GAIN_0_MASK	0xF0
#define QUASAR_GC2_TX_GAIN_0_OFFSET	0x4
#define QUASAR_GC2_TX_GAIN_0_DEFAULT	0x0

#define QUASAR_GC2_TX_GAIN_1_MASK	0xF
#define QUASAR_GC2_TX_GAIN_1_OFFSET	0x0
#define QUASAR_GC2_TX_GAIN_1_DEFAULT	0x0
#define QUASAR_GC2_DEFAULT		0x0

// ------------------------------------------------------------------- 
#define QUASAR_GC3_REG	QUASAR_BASE + 0xA

#define QUASAR_GC3_RSVD_MASK	0x3C000
#define QUASAR_GC3_RSVD_OFFSET	0xE
#define QUASAR_GC3_RSVD_DEFAULT	0x0

#define QUASAR_GC3_RX_GAIN_2_MASK	0x3F80
#define QUASAR_GC3_RX_GAIN_2_OFFSET	0x7
#define QUASAR_GC3_RX_GAIN_2_DEFAULT	0x0

#define QUASAR_GC3_RX_GAIN_1_MASK	0x7F
#define QUASAR_GC3_RX_GAIN_1_OFFSET	0x0
#define QUASAR_GC3_RX_GAIN_1_DEFAULT	0x0
#define QUASAR_GC3_DEFAULT		0x0

// ------------------------------------------------------------------- 
#define QUASAR_GC4_REG	QUASAR_BASE + 0xB

#define QUASAR_GC4_RSVD_MASK	0x3FF80
#define QUASAR_GC4_RSVD_OFFSET	0x7
#define QUASAR_GC4_RSVD_DEFAULT	0x0

#define QUASAR_GC4_RX_GAIN_0_MASK	0x7F
#define QUASAR_GC4_RX_GAIN_0_OFFSET	0x0
#define QUASAR_GC4_RX_GAIN_0_DEFAULT	0x0
#define QUASAR_GC4_DEFAULT		0x0

// ------------------------------------------------------------------- 
#define QUASAR_DCOC0_REG	QUASAR_BASE + 0xC

#define QUASAR_DCOC0_RSVD_MASK	0x30000
#define QUASAR_DCOC0_RSVD_OFFSET	0x10
#define QUASAR_DCOC0_RSVD_DEFAULT	0x0

#define QUASAR_DCOC0_RX0DC_RANGE_MASK	0xC000
#define QUASAR_DCOC0_RX0DC_RANGE_OFFSET	0xE
#define QUASAR_DCOC0_RX0DC_RANGE_DEFAULT	0x0
#define QUASAR_DCOC0_RX0DC_RANGE_E66P66_UA	0x0
#define QUASAR_DCOC0_RX0DC_RANGE_E133P33_UA	0x1
#define QUASAR_DCOC0_RX0DC_RANGE_E200_UA	0x2
#define QUASAR_DCOC0_RX0DC_RANGE_E266P66_UA	0x3

#define QUASAR_DCOC0_RX0DCI_MASK	0x3F80
#define QUASAR_DCOC0_RX0DCI_OFFSET	0x7
#define QUASAR_DCOC0_RX0DCI_DEFAULT	0x2000

#define QUASAR_DCOC0_RX0DCQ_MASK	0x7F
#define QUASAR_DCOC0_RX0DCQ_OFFSET	0x0
#define QUASAR_DCOC0_RX0DCQ_DEFAULT	0x40
#define QUASAR_DCOC0_DEFAULT		0x2040

// ------------------------------------------------------------------- 
#define QUASAR_DCOC1_REG	QUASAR_BASE + 0xD

#define QUASAR_DCOC1_RSVD_MASK	0x30000
#define QUASAR_DCOC1_RSVD_OFFSET	0x10
#define QUASAR_DCOC1_RSVD_DEFAULT	0x0

#define QUASAR_DCOC1_RX1DC_RANGE_MASK	0xC000
#define QUASAR_DCOC1_RX1DC_RANGE_OFFSET	0xE
#define QUASAR_DCOC1_RX1DC_RANGE_DEFAULT	0x0
#define QUASAR_DCOC1_RX1DC_RANGE_E66P66_UA	0x0
#define QUASAR_DCOC1_RX1DC_RANGE_E133P33_UA	0x1
#define QUASAR_DCOC1_RX1DC_RANGE_E200_UA	0x2
#define QUASAR_DCOC1_RX1DC_RANGE_E266P66_UA	0x3

#define QUASAR_DCOC1_RX1DCI_MASK	0x3F80
#define QUASAR_DCOC1_RX1DCI_OFFSET	0x7
#define QUASAR_DCOC1_RX1DCI_DEFAULT	0x2000

#define QUASAR_DCOC1_RX1DCQ_MASK	0x7F
#define QUASAR_DCOC1_RX1DCQ_OFFSET	0x0
#define QUASAR_DCOC1_RX1DCQ_DEFAULT	0x40
#define QUASAR_DCOC1_DEFAULT		0x2040

// ------------------------------------------------------------------- 
#define QUASAR_DCOC2_REG	QUASAR_BASE + 0xE

#define QUASAR_DCOC2_RX2DC_RANGE_MASK	0xC000
#define QUASAR_DCOC2_RX2DC_RANGE_OFFSET	0xE
#define QUASAR_DCOC2_RX2DC_RANGE_DEFAULT	0x0
#define QUASAR_DCOC2_RX2DC_RANGE_E66P66_UA	0x0
#define QUASAR_DCOC2_RX2DC_RANGE_E133P33_UA	0x1
#define QUASAR_DCOC2_RX2DC_RANGE_E200_UA	0x2
#define QUASAR_DCOC2_RX2DC_RANGE_E266P66_UA	0x3

#define QUASAR_DCOC2_RX2DCI_MASK	0x3F80
#define QUASAR_DCOC2_RX2DCI_OFFSET	0x7
#define QUASAR_DCOC2_RX2DCI_DEFAULT	0x2000

#define QUASAR_DCOC2_RX2DCQ_MASK	0x7F
#define QUASAR_DCOC2_RX2DCQ_OFFSET	0x0
#define QUASAR_DCOC2_RX2DCQ_DEFAULT	0x40
#define QUASAR_DCOC2_DEFAULT		0x2040

// ------------------------------------------------------------------- 
#define QUASAR_CFG1_REG	QUASAR_BASE + 0xF

#define QUASAR_CFG1_CLIP_EN_0_MASK	0x20000
#define QUASAR_CFG1_CLIP_EN_0_OFFSET	0x11
#define QUASAR_CFG1_CLIP_EN_0_DEFAULT	0x20000

#define QUASAR_CFG1_CLIP_EN_1_MASK	0x10000
#define QUASAR_CFG1_CLIP_EN_1_OFFSET	0x10
#define QUASAR_CFG1_CLIP_EN_1_DEFAULT	0x10000

#define QUASAR_CFG1_CLIP_EN_2_MASK	0x8000
#define QUASAR_CFG1_CLIP_EN_2_OFFSET	0xF
#define QUASAR_CFG1_CLIP_EN_2_DEFAULT	0x8000

#define QUASAR_CFG1_MOD_INV_MASK	0x7000
#define QUASAR_CFG1_MOD_INV_OFFSET	0xC
#define QUASAR_CFG1_MOD_INV_DEFAULT	0x0

#define QUASAR_CFG1_TX_RFLO_MASK	0x800
#define QUASAR_CFG1_TX_RFLO_OFFSET	0xB
#define QUASAR_CFG1_TX_RFLO_DEFAULT	0x0
#define QUASAR_CFG1_TX_RFLO_E200MV	0x0
#define QUASAR_CFG1_TX_RFLO_E300MV	0x1

#define QUASAR_CFG1_TX_IFLO_MASK	0x400
#define QUASAR_CFG1_TX_IFLO_OFFSET	0xA
#define QUASAR_CFG1_TX_IFLO_DEFAULT	0x0
#define QUASAR_CFG1_TX_IFLO_E200MV	0x0
#define QUASAR_CFG1_TX_IFLO_E300MV	0x1

#define QUASAR_CFG1_XO_DRV_MASK	0x300
#define QUASAR_CFG1_XO_DRV_OFFSET	0x8
#define QUASAR_CFG1_XO_DRV_DEFAULT	0x0

#define QUASAR_CFG1_XO_BYP_MASK	0x80
#define QUASAR_CFG1_XO_BYP_OFFSET	0x7
#define QUASAR_CFG1_XO_BYP_DEFAULT	0x0
#define QUASAR_CFG1_XO_BYP_EOSC	0x0
#define QUASAR_CFG1_XO_BYP_ETCXO	0x1

#define QUASAR_CFG1_XO_BUF_EN_MASK	0x40
#define QUASAR_CFG1_XO_BUF_EN_OFFSET	0x6
#define QUASAR_CFG1_XO_BUF_EN_DEFAULT	0x40

#define QUASAR_CFG1_TOUT_MASK	0x3E
#define QUASAR_CFG1_TOUT_OFFSET	0x1
#define QUASAR_CFG1_TOUT_DEFAULT	0x0

#define QUASAR_CFG1_TEN_MASK	0x1
#define QUASAR_CFG1_TEN_OFFSET	0x0
#define QUASAR_CFG1_TEN_DEFAULT	0x0
#define QUASAR_CFG1_DEFAULT		0x38040

// ------------------------------------------------------------------- 
#define QUASAR_CFG2_REG	QUASAR_BASE + 0x10

#define QUASAR_CFG2_RSVD_MASK	0x20000
#define QUASAR_CFG2_RSVD_OFFSET	0x11
#define QUASAR_CFG2_RSVD_DEFAULT	0x0

#define QUASAR_CFG2_RC_ATUNE_VAL_MASK	0x1FC00
#define QUASAR_CFG2_RC_ATUNE_VAL_OFFSET	0xA
#define QUASAR_CFG2_RC_ATUNE_VAL_DEFAULT	0x0

#define QUASAR_CFG2_RC_TUNE_EN_MASK	0x200
#define QUASAR_CFG2_RC_TUNE_EN_OFFSET	0x9
#define QUASAR_CFG2_RC_TUNE_EN_DEFAULT	0x0

#define QUASAR_CFG2_BBF_RX_TUNE_MASK	0x1E0
#define QUASAR_CFG2_BBF_RX_TUNE_OFFSET	0x5
#define QUASAR_CFG2_BBF_RX_TUNE_DEFAULT	0x0
#define QUASAR_CFG2_BBF_RX_TUNE_E50_MHZ	0x0
#define QUASAR_CFG2_BBF_RX_TUNE_E39P5_MHZ	0x1
#define QUASAR_CFG2_BBF_RX_TUNE_E32P6_MHZ	0x2
#define QUASAR_CFG2_BBF_RX_TUNE_E27P8_MHZ	0x3
#define QUASAR_CFG2_BBF_RX_TUNE_E24P2_MHZ	0x4
#define QUASAR_CFG2_BBF_RX_TUNE_E21P4_MHZ	0x5
#define QUASAR_CFG2_BBF_RX_TUNE_E19P2_MHZ	0x6
#define QUASAR_CFG2_BBF_RX_TUNE_E17P4_MHZ	0x7
#define QUASAR_CFG2_BBF_RX_TUNE_E16_MHZ	0x8
#define QUASAR_CFG2_BBF_RX_TUNE_E14P7_MHZ	0x9
#define QUASAR_CFG2_BBF_RX_TUNE_E13P6_MHZ	0xA
#define QUASAR_CFG2_BBF_RX_TUNE_E12P7_MHZ	0xB
#define QUASAR_CFG2_BBF_RX_TUNE_E11P9_MHZ	0xC
#define QUASAR_CFG2_BBF_RX_TUNE_E11P2_MHZ	0xD
#define QUASAR_CFG2_BBF_RX_TUNE_E10P6_MHZ	0xE
#define QUASAR_CFG2_BBF_RX_TUNE_E10_MHZ	0xF

#define QUASAR_CFG2_BBF_TX_TUNE_MASK	0x1E
#define QUASAR_CFG2_BBF_TX_TUNE_OFFSET	0x1
#define QUASAR_CFG2_BBF_TX_TUNE_DEFAULT	0x0
#define QUASAR_CFG2_BBF_TX_TUNE_E50_MHZ	0x0
#define QUASAR_CFG2_BBF_TX_TUNE_E39P5_MHZ	0x1
#define QUASAR_CFG2_BBF_TX_TUNE_E32P6_MHZ	0x2
#define QUASAR_CFG2_BBF_TX_TUNE_E27P8_MHZ	0x3
#define QUASAR_CFG2_BBF_TX_TUNE_E24P2_MHZ	0x4
#define QUASAR_CFG2_BBF_TX_TUNE_E21P4_MHZ	0x5
#define QUASAR_CFG2_BBF_TX_TUNE_E19P2_MHZ	0x6
#define QUASAR_CFG2_BBF_TX_TUNE_E17P4_MHZ	0x7
#define QUASAR_CFG2_BBF_TX_TUNE_E16_MHZ	0x8
#define QUASAR_CFG2_BBF_TX_TUNE_E14P7_MHZ	0x9
#define QUASAR_CFG2_BBF_TX_TUNE_E13P6_MHZ	0xA
#define QUASAR_CFG2_BBF_TX_TUNE_E12P7_MHZ	0xB
#define QUASAR_CFG2_BBF_TX_TUNE_E11P9_MHZ	0xC
#define QUASAR_CFG2_BBF_TX_TUNE_E11P2_MHZ	0xD
#define QUASAR_CFG2_BBF_TX_TUNE_E10P6_MHZ	0xE
#define QUASAR_CFG2_BBF_TX_TUNE_E10_MHZ	0xF

#define QUASAR_CFG2_BBF_ATUNE_EN_MASK	0x1
#define QUASAR_CFG2_BBF_ATUNE_EN_OFFSET	0x0
#define QUASAR_CFG2_BBF_ATUNE_EN_DEFAULT	0x0
#define QUASAR_CFG2_DEFAULT		0x0

// ------------------------------------------------------------------- 
#define QUASAR_CFG3_REG	QUASAR_BASE + 0x11

#define QUASAR_CFG3_RX2_DCOC_EN_MASK	0x20000
#define QUASAR_CFG3_RX2_DCOC_EN_OFFSET	0x11
#define QUASAR_CFG3_RX2_DCOC_EN_DEFAULT	0x20000

#define QUASAR_CFG3_RX1_DCOC_EN_MASK	0x10000
#define QUASAR_CFG3_RX1_DCOC_EN_OFFSET	0x10
#define QUASAR_CFG3_RX1_DCOC_EN_DEFAULT	0x10000

#define QUASAR_CFG3_RX0_DCOC_EN_MASK	0x8000
#define QUASAR_CFG3_RX0_DCOC_EN_OFFSET	0xF
#define QUASAR_CFG3_RX0_DCOC_EN_DEFAULT	0x8000

#define QUASAR_CFG3_TX1_D_MASK	0x7C00
#define QUASAR_CFG3_TX1_D_OFFSET	0xA
#define QUASAR_CFG3_TX1_D_DEFAULT	0x0

#define QUASAR_CFG3_TX1D_D_MASK	0x3E0
#define QUASAR_CFG3_TX1D_D_OFFSET	0x5
#define QUASAR_CFG3_TX1D_D_DEFAULT	0x0

#define QUASAR_CFG3_RX1_D_MASK	0x1F
#define QUASAR_CFG3_RX1_D_OFFSET	0x0
#define QUASAR_CFG3_RX1_D_DEFAULT	0x0
#define QUASAR_CFG3_DEFAULT		0x38000

// ------------------------------------------------------------------- 
#define QUASAR_CFG4_REG	QUASAR_BASE + 0x12

#define QUASAR_CFG4_CLK_GATE_MASK	0x20000
#define QUASAR_CFG4_CLK_GATE_OFFSET	0x11
#define QUASAR_CFG4_CLK_GATE_DEFAULT	0x20000

#define QUASAR_CFG4_TX_DBIAS_MASK	0x18000
#define QUASAR_CFG4_TX_DBIAS_OFFSET	0xF
#define QUASAR_CFG4_TX_DBIAS_DEFAULT	0x10000
#define QUASAR_CFG4_TX_DBIAS_E125UA	0x0
#define QUASAR_CFG4_TX_DBIAS_E250UA	0x1
#define QUASAR_CFG4_TX_DBIAS_E375UA	0x2
#define QUASAR_CFG4_TX_DBIAS_E500UA	0x3

#define QUASAR_CFG4_TX0_D_MASK	0x7C00
#define QUASAR_CFG4_TX0_D_OFFSET	0xA
#define QUASAR_CFG4_TX0_D_DEFAULT	0x0

#define QUASAR_CFG4_TX0D_D_MASK	0x3E0
#define QUASAR_CFG4_TX0D_D_OFFSET	0x5
#define QUASAR_CFG4_TX0D_D_DEFAULT	0x0

#define QUASAR_CFG4_RX0_D_MASK	0x1F
#define QUASAR_CFG4_RX0_D_OFFSET	0x0
#define QUASAR_CFG4_RX0_D_DEFAULT	0x0
#define QUASAR_CFG4_DEFAULT		0x30000

// ------------------------------------------------------------------- 
#define QUASAR_CFG5_REG	QUASAR_BASE + 0x13

#define QUASAR_CFG5_RX_IBIAS_EN_MASK	0x20000
#define QUASAR_CFG5_RX_IBIAS_EN_OFFSET	0x11
#define QUASAR_CFG5_RX_IBIAS_EN_DEFAULT	0x20000

#define QUASAR_CFG5_RX_RF_MIX_EN_MASK	0x10000
#define QUASAR_CFG5_RX_RF_MIX_EN_OFFSET	0x10
#define QUASAR_CFG5_RX_RF_MIX_EN_DEFAULT	0x10000

#define QUASAR_CFG5_RX_IF_MIX_EN_MASK	0x8000
#define QUASAR_CFG5_RX_IF_MIX_EN_OFFSET	0xF
#define QUASAR_CFG5_RX_IF_MIX_EN_DEFAULT	0x8000

#define QUASAR_CFG5_RX_IF_TUN_MASK	0x7800
#define QUASAR_CFG5_RX_IF_TUN_OFFSET	0xB
#define QUASAR_CFG5_RX_IF_TUN_DEFAULT	0x0
#define QUASAR_CFG5_RX_IF_TUN_E1500MHZ_OR_739MHZ	0x0
#define QUASAR_CFG5_RX_IF_TUN_E1530MHZ_OR_742MHZ	0x1
#define QUASAR_CFG5_RX_IF_TUN_E1560MHZ_OR_758MHZ	0x2
#define QUASAR_CFG5_RX_IF_TUN_E1590MHZ_OR_775MHZ	0x3
#define QUASAR_CFG5_RX_IF_TUN_E1620MHZ_OR_813MHZ	0x4
#define QUASAR_CFG5_RX_IF_TUN_E1650MHZ_OR_834MHZ	0x5
#define QUASAR_CFG5_RX_IF_TUN_E1690MHZ_OR_856MHZ	0x6
#define QUASAR_CFG5_RX_IF_TUN_E1730MHZ_OR_881MHZ	0x7
#define QUASAR_CFG5_RX_IF_TUN_E1770MHZ_OR_NA	0x8
#define QUASAR_CFG5_RX_IF_TUN_E1810MHZ_OR_NA	0x9
#define QUASAR_CFG5_RX_IF_TUN_E1850MHZ_OR_NA	0xA
#define QUASAR_CFG5_RX_IF_TUN_E1910MHZ_OR_NA	0xB
#define QUASAR_CFG5_RX_IF_TUN_E1970MHZ_OR_NA	0xC
#define QUASAR_CFG5_RX_IF_TUN_E2030MHZ_OR_NA	0xD
#define QUASAR_CFG5_RX_IF_TUN_E2100MHZ_OR_NA	0xE
#define QUASAR_CFG5_RX_IF_TUN_E2170MHZ_OR_NA	0xF

#define QUASAR_CFG5_TX_RF_TUN_MASK	0x700
#define QUASAR_CFG5_TX_RF_TUN_OFFSET	0x8
#define QUASAR_CFG5_TX_RF_TUN_DEFAULT	0x100
#define QUASAR_CFG5_TX_RF_TUN_E6P1GHZ_OR_2P6GHZ	0x0
#define QUASAR_CFG5_TX_RF_TUN_E5P9GHZ_OR_2P45GHZ	0x1
#define QUASAR_CFG5_TX_RF_TUN_E5P7GHZ_OR_NA	0x2
#define QUASAR_CFG5_TX_RF_TUN_E5P5GHZ_OR_2P3GHZ	0x3
#define QUASAR_CFG5_TX_RF_TUN_E5P3GHZ_OR_2P6GHZ	0x4
#define QUASAR_CFG5_TX_RF_TUN_E5P1GHZ_OR_2P45GHZ	0x5
#define QUASAR_CFG5_TX_RF_TUN_E5GHZ_OR_NA	0x6
#define QUASAR_CFG5_TX_RF_TUN_E4P9GHZ_OR_2P3GHZ	0x7

#define QUASAR_CFG5_TX_IF_TUN_MASK	0xE0
#define QUASAR_CFG5_TX_IF_TUN_OFFSET	0x5
#define QUASAR_CFG5_TX_IF_TUN_DEFAULT	0x20
#define QUASAR_CFG5_TX_IF_TUN_E2P1GHZ_OR_900MHZ	0x0
#define QUASAR_CFG5_TX_IF_TUN_E1P9GHZ_OR_825MHZ	0x1
#define QUASAR_CFG5_TX_IF_TUN_E1P8GHZ_OR_750MHZ	0x3
#define QUASAR_CFG5_TX_IF_TUN_E1P6GHZ_OR_750MHZ	0x7

#define QUASAR_CFG5_RX2_D_MASK	0x1F
#define QUASAR_CFG5_RX2_D_OFFSET	0x0
#define QUASAR_CFG5_RX2_D_DEFAULT	0x0
#define QUASAR_CFG5_DEFAULT		0x38120

// ------------------------------------------------------------------- 
#define QUASAR_CFG6_REG	QUASAR_BASE + 0x14

#define QUASAR_CFG6_RSVD_MASK	0x30000
#define QUASAR_CFG6_RSVD_OFFSET	0x10
#define QUASAR_CFG6_RSVD_DEFAULT	0x0

#define QUASAR_CFG6_RX_CASC_GC_MASK	0xE000
#define QUASAR_CFG6_RX_CASC_GC_OFFSET	0xD
#define QUASAR_CFG6_RX_CASC_GC_DEFAULT	0x0

#define QUASAR_CFG6_TX_CASC_GC_MASK	0x1800
#define QUASAR_CFG6_TX_CASC_GC_OFFSET	0xB
#define QUASAR_CFG6_TX_CASC_GC_DEFAULT	0x0
#define QUASAR_CFG6_TX_CASC_GC_ETX0_LOW_TX1_LOW	0x0
#define QUASAR_CFG6_TX_CASC_GC_ETX0_HIGH_TX1_LOW	0x1
#define QUASAR_CFG6_TX_CASC_GC_ETX0_LOW_TX1_HIGH	0x2
#define QUASAR_CFG6_TX_CASC_GC_ETX0_HIGH_TX1_HIGH	0x3

#define QUASAR_CFG6_RX_IF_LODRV_EN_MASK	0x400
#define QUASAR_CFG6_RX_IF_LODRV_EN_OFFSET	0xA
#define QUASAR_CFG6_RX_IF_LODRV_EN_DEFAULT	0x400

#define QUASAR_CFG6_XO_GM_MASK	0x300
#define QUASAR_CFG6_XO_GM_OFFSET	0x8
#define QUASAR_CFG6_XO_GM_DEFAULT	0x0

#define QUASAR_CFG6_CLIP_TEST_MASK	0x80
#define QUASAR_CFG6_CLIP_TEST_OFFSET	0x7
#define QUASAR_CFG6_CLIP_TEST_DEFAULT	0x0
#define QUASAR_CFG6_CLIP_TEST_ELATCH	0x0
#define QUASAR_CFG6_CLIP_TEST_ENO_LATCH	0x1

#define QUASAR_CFG6_CLIP_FREQ_MASK	0x40
#define QUASAR_CFG6_CLIP_FREQ_OFFSET	0x6
#define QUASAR_CFG6_CLIP_FREQ_DEFAULT	0x0
#define QUASAR_CFG6_CLIP_FREQ_E16MHZ	0x0
#define QUASAR_CFG6_CLIP_FREQ_E8MHZ	0x1

#define QUASAR_CFG6_CLIP_DET_TH_MASK	0x38
#define QUASAR_CFG6_CLIP_DET_TH_OFFSET	0x3
#define QUASAR_CFG6_CLIP_DET_TH_DEFAULT	0x8
#define QUASAR_CFG6_CLIP_DET_TH_E10DBC	0x0
#define QUASAR_CFG6_CLIP_DET_TH_E12DBC	0x1
#define QUASAR_CFG6_CLIP_DET_TH_E14DBC	0x2
#define QUASAR_CFG6_CLIP_DET_TH_E16DBC	0x3
#define QUASAR_CFG6_CLIP_DET_TH_E18DBC	0x4
#define QUASAR_CFG6_CLIP_DET_TH_E20DBC	0x5
#define QUASAR_CFG6_CLIP_DET_TH_E22DBC	0x6
#define QUASAR_CFG6_CLIP_DET_TH_E24DBC	0x7

#define QUASAR_CFG6_BBF_BIAS_MODE_MASK	0x4
#define QUASAR_CFG6_BBF_BIAS_MODE_OFFSET	0x2
#define QUASAR_CFG6_BBF_BIAS_MODE_DEFAULT	0x4

#define QUASAR_CFG6_TX_REG_MODE_MASK	0x2
#define QUASAR_CFG6_TX_REG_MODE_OFFSET	0x1
#define QUASAR_CFG6_TX_REG_MODE_DEFAULT	0x2

#define QUASAR_CFG6_TX_VREG_BYP_MASK	0x1
#define QUASAR_CFG6_TX_VREG_BYP_OFFSET	0x0
#define QUASAR_CFG6_TX_VREG_BYP_DEFAULT	0x0
#define QUASAR_CFG6_DEFAULT		0x40E

// ------------------------------------------------------------------- 
#define QUASAR_TEST1_REG	QUASAR_BASE + 0x15

#define QUASAR_TEST1_NDIV_OUT_MASK	0x20000
#define QUASAR_TEST1_NDIV_OUT_OFFSET	0x11
#define QUASAR_TEST1_NDIV_OUT_DEFAULT	0x0

#define QUASAR_TEST1_RX_LB_GAIN_MASK	0x10000
#define QUASAR_TEST1_RX_LB_GAIN_OFFSET	0x10
#define QUASAR_TEST1_RX_LB_GAIN_DEFAULT	0x0
#define QUASAR_TEST1_RX_LB_GAIN_EMINUS_10DB	0x0
#define QUASAR_TEST1_RX_LB_GAIN_E0DB	0x1

#define QUASAR_TEST1_TX_LB_GAIN_MASK	0x8000
#define QUASAR_TEST1_TX_LB_GAIN_OFFSET	0xF
#define QUASAR_TEST1_TX_LB_GAIN_DEFAULT	0x0
#define QUASAR_TEST1_TX_LB_GAIN_EMINUS_10DB	0x0
#define QUASAR_TEST1_TX_LB_GAIN_E0DB	0x1

#define QUASAR_TEST1_TEST_LB_RF_MASK	0x7000
#define QUASAR_TEST1_TEST_LB_RF_OFFSET	0xC
#define QUASAR_TEST1_TEST_LB_RF_DEFAULT	0x0

#define QUASAR_TEST1_RX_IQ_TEST_0_MASK	0x800
#define QUASAR_TEST1_RX_IQ_TEST_0_OFFSET	0xB
#define QUASAR_TEST1_RX_IQ_TEST_0_DEFAULT	0x0

#define QUASAR_TEST1_RX_IQ_TEST_1_MASK	0x400
#define QUASAR_TEST1_RX_IQ_TEST_1_OFFSET	0xA
#define QUASAR_TEST1_RX_IQ_TEST_1_DEFAULT	0x0

#define QUASAR_TEST1_RX_IQ_TEST_2_1_MASK	0x200
#define QUASAR_TEST1_RX_IQ_TEST_2_1_OFFSET	0x9
#define QUASAR_TEST1_RX_IQ_TEST_2_1_DEFAULT	0x0

#define QUASAR_TEST1_RX_IQ_TEST_2_0_MASK	0x100
#define QUASAR_TEST1_RX_IQ_TEST_2_0_OFFSET	0x8
#define QUASAR_TEST1_RX_IQ_TEST_2_0_DEFAULT	0x0

#define QUASAR_TEST1_TX_CAL_EN_0_MASK	0x80
#define QUASAR_TEST1_TX_CAL_EN_0_OFFSET	0x7
#define QUASAR_TEST1_TX_CAL_EN_0_DEFAULT	0x0

#define QUASAR_TEST1_TX_CAL_EN_1_MASK	0x40
#define QUASAR_TEST1_TX_CAL_EN_1_OFFSET	0x6
#define QUASAR_TEST1_TX_CAL_EN_1_DEFAULT	0x0

#define QUASAR_TEST1_DET_OFFSET_MASK	0x30
#define QUASAR_TEST1_DET_OFFSET_OFFSET	0x4
#define QUASAR_TEST1_DET_OFFSET_DEFAULT	0x0
#define QUASAR_TEST1_DET_OFFSET_E0V	0x0
#define QUASAR_TEST1_DET_OFFSET_E0P5V	0x1
#define QUASAR_TEST1_DET_OFFSET_E1V	0x2

#define QUASAR_TEST1_DET_GAIN_MASK	0xE
#define QUASAR_TEST1_DET_GAIN_OFFSET	0x1
#define QUASAR_TEST1_DET_GAIN_DEFAULT	0x0

#define QUASAR_TEST1_RDIV_TEST_MASK	0x1
#define QUASAR_TEST1_RDIV_TEST_OFFSET	0x0
#define QUASAR_TEST1_RDIV_TEST_DEFAULT	0x0
#define QUASAR_TEST1_DEFAULT		0x0

// ------------------------------------------------------------------- 
#define QUASAR_TEST2_REG	QUASAR_BASE + 0x16

#define QUASAR_TEST2_RSVD_MASK	0x20000
#define QUASAR_TEST2_RSVD_OFFSET	0x11
#define QUASAR_TEST2_RSVD_DEFAULT	0x0

#define QUASAR_TEST2_TX_DRVR_GAIN_MASK	0x10000
#define QUASAR_TEST2_TX_DRVR_GAIN_OFFSET	0x10
#define QUASAR_TEST2_TX_DRVR_GAIN_DEFAULT	0x10000

#define QUASAR_TEST2_TX_VGA_GAIN_MASK	0xF000
#define QUASAR_TEST2_TX_VGA_GAIN_OFFSET	0xC
#define QUASAR_TEST2_TX_VGA_GAIN_DEFAULT	0xF000

#define QUASAR_TEST2_TX_IQ_GAIN_MASK	0xE00
#define QUASAR_TEST2_TX_IQ_GAIN_OFFSET	0x9
#define QUASAR_TEST2_TX_IQ_GAIN_DEFAULT	0xC00

#define QUASAR_TEST2_TX_GTEST_MASK	0x100
#define QUASAR_TEST2_TX_GTEST_OFFSET	0x8
#define QUASAR_TEST2_TX_GTEST_DEFAULT	0x0

#define QUASAR_TEST2_BBF_IBIAS_CTL_MASK	0xFF
#define QUASAR_TEST2_BBF_IBIAS_CTL_OFFSET	0x0
#define QUASAR_TEST2_BBF_IBIAS_CTL_DEFAULT	0x0
#define QUASAR_TEST2_DEFAULT		0x1FC00

// ------------------------------------------------------------------- 
#define QUASAR_TEST3_REG	QUASAR_BASE + 0x17

#define QUASAR_TEST3_BBF_TEST_I_MASK	0x3F000
#define QUASAR_TEST3_BBF_TEST_I_OFFSET	0xC
#define QUASAR_TEST3_BBF_TEST_I_DEFAULT	0x0
#define QUASAR_TEST3_BBF_TEST_I_ENORMAL	0x0
#define QUASAR_TEST3_BBF_TEST_I_ETEST_OUT_EN	0x1
#define QUASAR_TEST3_BBF_TEST_I_EI_V_OUTPUT	0x2
#define QUASAR_TEST3_BBF_TEST_I_EGAIN1_OUTPUT	0x4
#define QUASAR_TEST3_BBF_TEST_I_EFILTER2_OUTPUT	0x8
#define QUASAR_TEST3_BBF_TEST_I_EFILTER3_OUTPUT	0x10
#define QUASAR_TEST3_BBF_TEST_I_EDRIVER_OUTPUT	0x20

#define QUASAR_TEST3_BBF_TEST_Q_MASK	0xFC0
#define QUASAR_TEST3_BBF_TEST_Q_OFFSET	0x6
#define QUASAR_TEST3_BBF_TEST_Q_DEFAULT	0x0
#define QUASAR_TEST3_BBF_TEST_Q_ENORMAL	0x0
#define QUASAR_TEST3_BBF_TEST_Q_ETEST_OUT_EN	0x1
#define QUASAR_TEST3_BBF_TEST_Q_EI_V_OUTPUT	0x2
#define QUASAR_TEST3_BBF_TEST_Q_EGAIN1_OUTPUT	0x4
#define QUASAR_TEST3_BBF_TEST_Q_EFILTER2_OUTPUT	0x8
#define QUASAR_TEST3_BBF_TEST_Q_EFILTER3_OUTPUT	0x10
#define QUASAR_TEST3_BBF_TEST_Q_EDRIVER_OUTPUT	0x20

#define QUASAR_TEST3_CT_VAL_AUTO_MASK	0x3F
#define QUASAR_TEST3_CT_VAL_AUTO_OFFSET	0x0
#define QUASAR_TEST3_CT_VAL_AUTO_DEFAULT	0x0
#define QUASAR_TEST3_DEFAULT		0x0

// ------------------------------------------------------------------- 
#define QUASAR_TEST4_REG	QUASAR_BASE + 0x18

#define QUASAR_TEST4_IO_TEST_MASK	0x20000
#define QUASAR_TEST4_IO_TEST_OFFSET	0x11
#define QUASAR_TEST4_IO_TEST_DEFAULT	0x0

#define QUASAR_TEST4_TX_RF_EN_MASK	0x10000
#define QUASAR_TEST4_TX_RF_EN_OFFSET	0x10
#define QUASAR_TEST4_TX_RF_EN_DEFAULT	0x10000
#define QUASAR_TEST4_TX_RF_EN_EDIS	0x0
#define QUASAR_TEST4_TX_RF_EN_EEN	0x1

#define QUASAR_TEST4_TX_DRVR_EN_MASK	0x8000
#define QUASAR_TEST4_TX_DRVR_EN_OFFSET	0xF
#define QUASAR_TEST4_TX_DRVR_EN_DEFAULT	0x8000
#define QUASAR_TEST4_TX_DRVR_EN_EDIS	0x0
#define QUASAR_TEST4_TX_DRVR_EN_EEN	0x1

#define QUASAR_TEST4_TX_IQ_EN_MASK	0x4000
#define QUASAR_TEST4_TX_IQ_EN_OFFSET	0xE
#define QUASAR_TEST4_TX_IQ_EN_DEFAULT	0x4000
#define QUASAR_TEST4_TX_IQ_EN_EDIS	0x0
#define QUASAR_TEST4_TX_IQ_EN_EEN	0x1

#define QUASAR_TEST4_BBF_ENQ_MASK	0x3F80
#define QUASAR_TEST4_BBF_ENQ_OFFSET	0x7
#define QUASAR_TEST4_BBF_ENQ_DEFAULT	0x3F80
#define QUASAR_TEST4_BBF_ENQ_ETX_CASCADE	0x1
#define QUASAR_TEST4_BBF_ENQ_EDC0_DAC	0x2
#define QUASAR_TEST4_BBF_ENQ_EI_V_OPAMP	0x4
#define QUASAR_TEST4_BBF_ENQ_EGAIN1_OPAMP	0x8
#define QUASAR_TEST4_BBF_ENQ_EFILTER2_OPAMP	0x10
#define QUASAR_TEST4_BBF_ENQ_EFILTER3_OPAMP	0x20
#define QUASAR_TEST4_BBF_ENQ_EDRIVER_OPAMP	0x40

#define QUASAR_TEST4_BBF_ENI_MASK	0x7F
#define QUASAR_TEST4_BBF_ENI_OFFSET	0x0
#define QUASAR_TEST4_BBF_ENI_DEFAULT	0x7F
#define QUASAR_TEST4_BBF_ENI_ETX_CASCADE	0x1
#define QUASAR_TEST4_BBF_ENI_EDC0_DAC	0x2
#define QUASAR_TEST4_BBF_ENI_EI_V_OPAMP	0x4
#define QUASAR_TEST4_BBF_ENI_EGAIN1_OPAMP	0x8
#define QUASAR_TEST4_BBF_ENI_EFILTER2_OPAMP	0x10
#define QUASAR_TEST4_BBF_ENI_EFILTER3_OPAMP	0x20
#define QUASAR_TEST4_BBF_ENI_EDRIVER_OPAMP	0x40
#define QUASAR_TEST4_DEFAULT		0x1FFFF

// ------------------------------------------------------------------- 
#define QUASAR_TEST5_REG	QUASAR_BASE + 0x19

#define QUASAR_TEST5_RX_GMTUNE_EN_MASK	0x20000
#define QUASAR_TEST5_RX_GMTUNE_EN_OFFSET	0x11
#define QUASAR_TEST5_RX_GMTUNE_EN_DEFAULT	0x0

#define QUASAR_TEST5_XO_REG_BYP_MASK	0x10000
#define QUASAR_TEST5_XO_REG_BYP_OFFSET	0x10
#define QUASAR_TEST5_XO_REG_BYP_DEFAULT	0x0
#define QUASAR_TEST5_XO_REG_BYP_ENO_BYPASS	0x0
#define QUASAR_TEST5_XO_REG_BYP_EBYPASS	0x1

#define QUASAR_TEST5_XO_PLL_BUF_EN_MASK	0x8000
#define QUASAR_TEST5_XO_PLL_BUF_EN_OFFSET	0xF
#define QUASAR_TEST5_XO_PLL_BUF_EN_DEFAULT	0x8000
#define QUASAR_TEST5_XO_PLL_BUF_EN_EDIS	0x0
#define QUASAR_TEST5_XO_PLL_BUF_EN_EEN	0x1

#define QUASAR_TEST5_ATEST_MASK	0x7E00
#define QUASAR_TEST5_ATEST_OFFSET	0x9
#define QUASAR_TEST5_ATEST_DEFAULT	0x0

#define QUASAR_TEST5_ATEST_EN_MASK	0x100
#define QUASAR_TEST5_ATEST_EN_OFFSET	0x8
#define QUASAR_TEST5_ATEST_EN_DEFAULT	0x0

#define QUASAR_TEST5_BBF_GAIN2_MASK	0xE0
#define QUASAR_TEST5_BBF_GAIN2_OFFSET	0x5
#define QUASAR_TEST5_BBF_GAIN2_DEFAULT	0x0
#define QUASAR_TEST5_BBF_GAIN2_E12DB	0x0
#define QUASAR_TEST5_BBF_GAIN2_E14DB	0x1
#define QUASAR_TEST5_BBF_GAIN2_EUNDEFINED	0x2
#define QUASAR_TEST5_BBF_GAIN2_E16DB	0x3
#define QUASAR_TEST5_BBF_GAIN2_E6DB	0x4
#define QUASAR_TEST5_BBF_GAIN2_E8DB	0x5
#define QUASAR_TEST5_BBF_GAIN2_E10DB	0x7

#define QUASAR_TEST5_BBF_GAIN1_MASK	0x1E
#define QUASAR_TEST5_BBF_GAIN1_OFFSET	0x1
#define QUASAR_TEST5_BBF_GAIN1_DEFAULT	0x0
#define QUASAR_TEST5_BBF_GAIN1_E12DB	0x0
#define QUASAR_TEST5_BBF_GAIN1_E14DB	0x1
#define QUASAR_TEST5_BBF_GAIN1_E16DB	0x3
#define QUASAR_TEST5_BBF_GAIN1_E6DB	0x8
#define QUASAR_TEST5_BBF_GAIN1_E8DB	0x9
#define QUASAR_TEST5_BBF_GAIN1_E10DB	0xB
#define QUASAR_TEST5_BBF_GAIN1_E0DB	0xC
#define QUASAR_TEST5_BBF_GAIN1_E2DB	0xD
#define QUASAR_TEST5_BBF_GAIN1_E4DB	0xF

#define QUASAR_TEST5_BBF_GAIN_TEST_MASK	0x1
#define QUASAR_TEST5_BBF_GAIN_TEST_OFFSET	0x0
#define QUASAR_TEST5_BBF_GAIN_TEST_DEFAULT	0x0
#define QUASAR_TEST5_BBF_GAIN_TEST_EGAIN_TABLE	0x0
#define QUASAR_TEST5_BBF_GAIN_TEST_EREGISTERS	0x1
#define QUASAR_TEST5_DEFAULT		0x8000

// ------------------------------------------------------------------- 
#define QUASAR_TEST6_REG	QUASAR_BASE + 0x1A

#define QUASAR_TEST6_TX1_DCOC_EN_MASK	0x20000
#define QUASAR_TEST6_TX1_DCOC_EN_OFFSET	0x11
#define QUASAR_TEST6_TX1_DCOC_EN_DEFAULT	0x0

#define QUASAR_TEST6_TX0_DCOC_EN_MASK	0x10000
#define QUASAR_TEST6_TX0_DCOC_EN_OFFSET	0x10
#define QUASAR_TEST6_TX0_DCOC_EN_DEFAULT	0x0

#define QUASAR_TEST6_TX0_DCOC_I_MASK	0xF800
#define QUASAR_TEST6_TX0_DCOC_I_OFFSET	0xB
#define QUASAR_TEST6_TX0_DCOC_I_DEFAULT	0x0

#define QUASAR_TEST6_TX0_DCOC_Q_MASK	0x7C0
#define QUASAR_TEST6_TX0_DCOC_Q_OFFSET	0x6
#define QUASAR_TEST6_TX0_DCOC_Q_DEFAULT	0x0
#define QUASAR_TEST6_TX0_DCOC_Q_EX0	0x0
#define QUASAR_TEST6_TX0_DCOC_Q_EX1	0x1
#define QUASAR_TEST6_TX0_DCOC_Q_EX15	0xF
#define QUASAR_TEST6_TX0_DCOC_Q_EX17	0x11
#define QUASAR_TEST6_TX0_DCOC_Q_EX31	0x1F

#define QUASAR_TEST6_ADC_TEST_MASK	0x3E
#define QUASAR_TEST6_ADC_TEST_OFFSET	0x1
#define QUASAR_TEST6_ADC_TEST_DEFAULT	0x0

#define QUASAR_TEST6_ADC_TEST_EN_MASK	0x1
#define QUASAR_TEST6_ADC_TEST_EN_OFFSET	0x0
#define QUASAR_TEST6_ADC_TEST_EN_DEFAULT	0x0
#define QUASAR_TEST6_ADC_TEST_EN_ENORMAL	0x0
#define QUASAR_TEST6_ADC_TEST_EN_ETEST	0x1
#define QUASAR_TEST6_DEFAULT		0x0

// ------------------------------------------------------------------- 
#define QUASAR_SPARES_REG	QUASAR_BASE + 0x1B

#define QUASAR_SPARES_RX_MAINT_MASK	0x20000
#define QUASAR_SPARES_RX_MAINT_OFFSET	0x11
#define QUASAR_SPARES_RX_MAINT_DEFAULT	0x0
#define QUASAR_SPARES_RX_MAINT_ETXRX	0x0
#define QUASAR_SPARES_RX_MAINT_ERX	0x1

#define QUASAR_SPARES_SPARES_MASK	0x1FC00
#define QUASAR_SPARES_SPARES_OFFSET	0xA
#define QUASAR_SPARES_SPARES_DEFAULT	0x0

#define QUASAR_SPARES_TX1_DCOC_I_MASK	0x3E0
#define QUASAR_SPARES_TX1_DCOC_I_OFFSET	0x5
#define QUASAR_SPARES_TX1_DCOC_I_DEFAULT	0x0

#define QUASAR_SPARES_TX1_DCOC_Q_MASK	0x1F
#define QUASAR_SPARES_TX1_DCOC_Q_OFFSET	0x0
#define QUASAR_SPARES_TX1_DCOC_Q_DEFAULT	0x0
#define QUASAR_SPARES_TX1_DCOC_Q_EX0	0x0
#define QUASAR_SPARES_TX1_DCOC_Q_EX1	0x1
#define QUASAR_SPARES_TX1_DCOC_Q_EX15	0xF
#define QUASAR_SPARES_TX1_DCOC_Q_EX17	0x11
#define QUASAR_SPARES_TX1_DCOC_Q_EX31	0x1F
#define QUASAR_SPARES_DEFAULT		0x0

// ------------------------------------------------------------------- 
#define QUASAR_RESET_REG	QUASAR_BASE + 0x1C

#define QUASAR_RESET_RESET_MASK	0x3FFFF
#define QUASAR_RESET_RESET_OFFSET	0x0
#define QUASAR_RESET_RESET_DEFAULT	0x0
#define QUASAR_RESET_DEFAULT		0x0

// ------------------------------------------------------------------- 
#define QUASAR_SPARE2_REG	QUASAR_BASE + 0x1D

#define QUASAR_SPARE2_SPARES2_MASK	0x3FFFF
#define QUASAR_SPARE2_SPARES2_OFFSET	0x0
#define QUASAR_SPARE2_SPARES2_DEFAULT	0x0
#define QUASAR_SPARE2_DEFAULT		0x0

// ------------------------------------------------------------------- 

#endif // __POLQUASAR_H
