/**
 *
   Airgo Networks, Inc proprietary.
   All Rights Reserved, Copyright 2005
   This program is the confidential and proprietary product of Airgo Networks Inc.
   Any Unauthorized use, reproduction or transfer of this program is strictly prohibited.


   rfQuasar.h: Quasar register definitions and macros
   Author:             Bharath Pandravada
   Date:               05/29/06

   History -
   Date        Modified by              Modification Information
  --------------------------------------------------------------------------

 */

#ifndef RFQUASAR_H
#define RFQUASAR_H

#include "quasar.h"
#include "wlan_bit.h"

//Quasar Definitions

typedef enum
{
    QUASAR_REG_PLL1                  =   0,
    QUASAR_REG_PLL2                  =   1,
    QUASAR_REG_PLL3                  =   2,
    QUASAR_REG_PLL4                  =   3,
    QUASAR_REG_PLL5                  =   4,
    QUASAR_REG_PLL6                  =   5,
    QUASAR_REG_LO_CONFIG             =   6,
    QUASAR_REG_STATE                 =   7,
    QUASAR_REG_GAIN_CONTROL_1        =   8,
    QUASAR_REG_GAIN_CONTROL_2        =   9,
    QUASAR_REG_GAIN_CONTROL_3        =   10,
    QUASAR_REG_GAIN_CONTROL_4        =   11,
    QUASAR_REG_DC_OFFSET_CHAIN_0     =   12,
    QUASAR_REG_DC_OFFSET_CHAIN_1     =   13,
    QUASAR_REG_DC_OFFSET_CHAIN_2     =   14,
    QUASAR_REG_CFG_1                 =   15,
    QUASAR_REG_CFG_2                 =   16,
    QUASAR_REG_CFG_3                 =   17,
    QUASAR_REG_CFG_4                 =   18,
    QUASAR_REG_CFG_5                 =   19,
    QUASAR_REG_CFG_6                 =   20,
    QUASAR_REG_TEST_1                =   21,
    QUASAR_REG_TEST_2                =   22,
    QUASAR_REG_TEST_3                =   23,
    QUASAR_REG_TEST_4                =   24,
    QUASAR_REG_TEST_5                =   25,
    QUASAR_REG_TEST_6                =   26,
    QUASAR_REG_SPARES                =   27,
    QUASAR_REG_RESET                 =   28,        //not readable
    QUASAR_REG_SPARES2               =   29,        //not readable

    QUASAR_NUM_REGS
}eQuasarRegs;



typedef enum
{
    //whole registers first
    QUASAR_PLL1,
    QUASAR_PLL2,
    QUASAR_PLL3,
    QUASAR_PLL4,
    QUASAR_PLL5,
    QUASAR_PLL6,
    QUASAR_LO_CONFIG,
    QUASAR_STATE,
    QUASAR_GAIN_CONTROL_1,
    QUASAR_GAIN_CONTROL_2,
    QUASAR_GAIN_CONTROL_3,
    QUASAR_GAIN_CONTROL_4,
    QUASAR_DC_OFFSET_CHAIN_0,
    QUASAR_DC_OFFSET_CHAIN_1,
    QUASAR_DC_OFFSET_CHAIN_2,
    QUASAR_CFG_1,
    QUASAR_CFG_2,
    QUASAR_CFG_3,
    QUASAR_CFG_4,
    QUASAR_CFG_5,
    QUASAR_CFG_6,
    QUASAR_TEST_1,
    QUASAR_TEST_2,
    QUASAR_TEST_3,
    QUASAR_TEST_4,
    QUASAR_TEST_5,
    QUASAR_TEST_6,
    QUASAR_SPARES,

    //fields
    QUASAR_FIELD_NDIV_INT,
    QUASAR_FIELD_NDIV_FRAC,
    QUASAR_FIELD_CP_GAIN,
    QUASAR_FIELD_NDIV_EN,
    QUASAR_FIELD_PFD_EN,
    QUASAR_FIELD_CP_EN,
    QUASAR_FIELD_FNZ,
    QUASAR_FIELD_PLL_CT_ACTIVE,
    QUASAR_FIELD_VCO_EN,
    QUASAR_FIELD_CT_EN,
    QUASAR_FIELD_RDIV,
    QUASAR_FIELD_EXT_RFLO_EN,
    QUASAR_FIELD_RFLO_OUT_EN,
    QUASAR_FIELD_PLL_CT_START,
    QUASAR_FIELD_PLL_ADC_AQ,
    QUASAR_FIELD_VTUNE_VAL,
    QUASAR_FIELD_CT_MAINT,
    QUASAR_FIELD_PLL_TUNE_ERR,
    QUASAR_FIELD_PLL_VREG_D,
    QUASAR_FIELD_PLL_VREG_EN,
    QUASAR_FIELD_VCO_VREG_EN,
    QUASAR_FIELD_VTUNE_RANGE,
    QUASAR_FIELD_CT_VAL,
    QUASAR_FIELD_VTUNE_T,
    QUASAR_FIELD_VCO_SEL,
    QUASAR_FIELD_CT_SETIME,
    QUASAR_FIELD_THREE_FOURB,
    QUASAR_FIELD_IBUF_BIAS,
    QUASAR_FIELD_VCO_BIAS,
    QUASAR_FIELD_CP_LOGIC,
    QUASAR_FIELD_FRAC_OFFS,
    QUASAR_FIELD_NDIV_BIAS,
    QUASAR_FIELD_LBW_CAL_SU,
    QUASAR_FIELD_CP_GAIN_CAL,
    QUASAR_FIELD_DELTA_NDIV,
    QUASAR_FIELD_PLL_TRANGE,
    QUASAR_FIELD_PLL_TGOAL,
    QUASAR_FIELD_LOOP_CAL_EN,
    QUASAR_FIELD_EXT_IFLO_EN,
    QUASAR_FIELD_IQ_DIV_EN,
    QUASAR_FIELD_NDIV_LO,
    QUASAR_FIELD_EXT_LO,
    QUASAR_FIELD_TX1_LO,
    QUASAR_FIELD_TX0_LO,
    QUASAR_FIELD_RX2_LO,
    QUASAR_FIELD_RX1_LO,
    QUASAR_FIELD_RX0_LO,
    QUASAR_FIELD_MS_REV,
    QUASAR_FIELD_XO_DISABLE_ST,
    QUASAR_FIELD_RX1_ST_EN,
    QUASAR_FIELD_RX_ALL_ST_EN,
    QUASAR_FIELD_TX_ST_EN,
    QUASAR_FIELD_PLL_EN,
    QUASAR_FIELD_TXRX_BAND,
    QUASAR_FIELD_MREV,
    QUASAR_FIELD_TWOG_HS_EN,
    QUASAR_FIELD_RXG_2,
    QUASAR_FIELD_RXG_1,
    QUASAR_FIELD_RXG_0,
    QUASAR_FIELD_GC_SELECT,
    QUASAR_FIELD_SPI_LUT_EN,
    QUASAR_FIELD_SPI_LUT_INDEX,
    QUASAR_FIELD_TX_GAIN_0,
    QUASAR_FIELD_TX_GAIN_1,
    QUASAR_FIELD_RX_GAIN_2,
    QUASAR_FIELD_RX_GAIN_1,
    QUASAR_FIELD_RX_GAIN_0,
    QUASAR_FIELD_RX0DC_RANGE,
    QUASAR_FIELD_RX0DCI,
    QUASAR_FIELD_RX0DCQ,
    QUASAR_FIELD_RX1DC_RANGE,
    QUASAR_FIELD_RX1DCI,
    QUASAR_FIELD_RX1DCQ,
    QUASAR_FIELD_RX2DC_RANGE,
    QUASAR_FIELD_RX2DCI,
    QUASAR_FIELD_RX2DCQ,
    QUASAR_FIELD_CLIP_EN_0,
    QUASAR_FIELD_CLIP_EN_1,
    QUASAR_FIELD_CLIP_EN_2,
    QUASAR_FIELD_MOD_INV,
    QUASAR_FIELD_TX_RFLO,
    QUASAR_FIELD_TX_IFLO,
    QUASAR_FIELD_XO_DRV,
    QUASAR_FIELD_XO_BYP,
    QUASAR_FIELD_XO_BUF_EN,
    QUASAR_FIELD_TOUT,
    QUASAR_FIELD_TEN,
    QUASAR_FIELD_RC_ATUNE_VAL,
    QUASAR_FIELD_RC_TUNE_EN,
    QUASAR_FIELD_BBF_RX_TUNE,
    QUASAR_FIELD_BBF_TX_TUNE,
    QUASAR_FIELD_BBF_ATUNE_EN,
    QUASAR_FIELD_RX2_DCOC_EN,
    QUASAR_FIELD_RX1_DCOC_EN,
    QUASAR_FIELD_RX0_DCOC_EN,
    QUASAR_FIELD_TX1_D,
    QUASAR_FIELD_TX1D_D,
    QUASAR_FIELD_RX1_D,
    QUASAR_FIELD_CLK_GATE,
    QUASAR_FIELD_TX_DBIAS,
    QUASAR_FIELD_TX0_D,
    QUASAR_FIELD_TX0D_D,
    QUASAR_FIELD_RX0_D,
    QUASAR_FIELD_RX_IBIAS_EN,
    QUASAR_FIELD_RX_RF_MIX_EN,
    QUASAR_FIELD_RX_IF_MIX_EN,
    QUASAR_FIELD_RX_IF_TUN,
    QUASAR_FIELD_TX_RF_TUN,
    QUASAR_FIELD_TX_IF_TUN,
    QUASAR_FIELD_RX2_D,
    QUASAR_FIELD_RX_CASC_GC,
    QUASAR_FIELD_TX_CASC_GC,
    QUASAR_FIELD_RX_IF_LODRV_EN,
    QUASAR_FIELD_XO_GM,
    QUASAR_FIELD_CLIP_TEST,
    QUASAR_FIELD_CLIP_FREQ,
    QUASAR_FIELD_CLIP_DET_TH,
    QUASAR_FIELD_BBF_BIAS_MODE,
    QUASAR_FIELD_TX_REG_MODE,
    QUASAR_FIELD_TX_VREG_BYP,
    QUASAR_FIELD_NDIV_OUT,
    QUASAR_FIELD_RX_LB_GAIN,
    QUASAR_FIELD_TX_LB_GAIN,
    QUASAR_FIELD_TEST_LB_RF,
    QUASAR_FIELD_RX_IQ_TEST_0,
    QUASAR_FIELD_RX_IQ_TEST_1,
    QUASAR_FIELD_RX_IQ_TEST_2_1,
    QUASAR_FIELD_RX_IQ_TEST_2_0,
    QUASAR_FIELD_TX_CAL_EN_0,
    QUASAR_FIELD_TX_CAL_EN_1,
    QUASAR_FIELD_DET_OFFSET,
    QUASAR_FIELD_DET_GAIN,
    QUASAR_FIELD_RDIV_TEST,
    QUASAR_FIELD_TX_DRVR_GAIN,
    QUASAR_FIELD_TX_VGA_GAIN,
    QUASAR_FIELD_TX_IQ_GAIN,
    QUASAR_FIELD_TX_GTEST,
    QUASAR_FIELD_BBF_IBIAS_CTL,
    QUASAR_FIELD_BBF_TEST_I,
    QUASAR_FIELD_BBF_TEST_Q,
    QUASAR_FIELD_CT_VAL_AUTO,
    QUASAR_FIELD_IO_TEST,
    QUASAR_FIELD_TX_RF_EN,
    QUASAR_FIELD_TX_DRVR_EN,
    QUASAR_FIELD_TX_IQ_EN,
    QUASAR_FIELD_BBF_ENQ,
    QUASAR_FIELD_BBF_ENI,
    QUASAR_FIELD_RX_GMTUNE_EN,
    QUASAR_FIELD_XO_REG_BYP,
    QUASAR_FIELD_XO_PLL_BUF_EN,
    QUASAR_FIELD_ATEST,
    QUASAR_FIELD_ATEST_EN,
    QUASAR_FIELD_BBF_GAIN2,
    QUASAR_FIELD_BBF_GAIN1,
    QUASAR_FIELD_BBF_GAIN_TEST,
    QUASAR_FIELD_TX1_DCOC_EN,
    QUASAR_FIELD_TX0_DCOC_EN,
    QUASAR_FIELD_TX0_DCOC_I,
    QUASAR_FIELD_TX0_DCOC_Q,
    QUASAR_FIELD_ADC_TEST,
    QUASAR_FIELD_ADC_TEST_EN,
    QUASAR_FIELD_RX_MAINT,
    QUASAR_FIELD_SPARES,
    QUASAR_FIELD_TX1_DCOC_I,
    QUASAR_FIELD_TX1_DCOC_Q,

    NUM_QUASAR_FIELDS
}eQuasarFields;


typedef enum
{
    QUASAR_LB_GAIN_ALL_LO = 0,  //tx & rx = -10dBm
    QUASAR_LB_GAIN_RX_LO = 1,   //tx = 0dBm, rx = -10dBm
    QUASAR_LB_GAIN_TX_LO = 2,   //tx = -10dBm, rx = 0dBm
    QUASAR_LB_GAIN_0DB = 3,     //both tx & rx LB gain = 0
}eQuasarLoopbackGain;





//Quasar Register 0 Fields
#define QUASAR_NDIV_INT_MASK            MSK_7
#define QUASAR_NDIV_FRAC_HI_MASK        MSK_2
#define QUASAR_CP_GAIN_MASK             MSK_5
#define QUASAR_NDIV_EN_MASK             MSK_1
#define QUASAR_PFD_EN_MASK              MSK_1
#define QUASAR_CP_EN_MASK               MSK_1
#define QUASAR_FNZ_MASK                 MSK_1

#define QUASAR_NDIV_INT_OFFSET          11
#define QUASAR_NDIV_FRAC_HI_OFFSET      9
#define QUASAR_CP_GAIN_OFFSET           4
#define QUASAR_NDIV_EN_OFFSET           3
#define QUASAR_PFD_EN_OFFSET            2
#define QUASAR_CP_EN_OFFSET             1
#define QUASAR_FNZ_OFFSET               0


//Quasar Register 1 Fields
#define QUASAR_NDIV_FRAC_LO_MASK        MSK_18

#define QUASAR_NDIV_FRAC_LO_OFFSET      0


//Quasar Register 2 Fields
#define QUASAR_PLL_CT_ACTIVE_MASK       MSK_1
#define QUASAR_VCO_EN_MASK              MSK_2
#define QUASAR_CT_EN_MASK               MSK_1
#define QUASAR_RDIV_MASK                MSK_2
#define QUASAR_EXT_RFLO_EN_MASK         MSK_1
#define QUASAR_RFLO_OUT_EN_MASK         MSK_1
#define QUASAR_PLL_CT_START_MASK        MSK_1
#define QUASAR_PLL_ADC_AQ_MASK          MSK_1
#define QUASAR_VTUNE_VAL_MASK           MSK_5
#define QUASAR_CT_MAINT_MASK            MSK_3

#define QUASAR_PLL_CT_ACTIVE_OFFSET     17
#define QUASAR_VCO_EN_OFFSET            15
#define QUASAR_CT_EN_OFFSET             14
#define QUASAR_RDIV_OFFSET              12
#define QUASAR_EXT_RFLO_EN_OFFSET       11
#define QUASAR_RFLO_OUT_EN_OFFSET       10
#define QUASAR_PLL_CT_START_OFFSET      9
#define QUASAR_PLL_ADC_AQ_OFFSET        8
#define QUASAR_VTUNE_VAL_OFFSET         3
#define QUASAR_CT_MAINT_OFFSET          0


//Quasar Register 3 Fields
#define QUASAR_PLL_TUNE_ERR_MASK        MSK_1
#define QUASAR_PLL_VREG_D_MASK          MSK_1
#define QUASAR_PLL_VREG_EN_MASK         MSK_1
#define QUASAR_VCO_VREG_EN_MASK         MSK_1
#define QUASAR_VTUNE_RANGE_MASK         MSK_2
#define QUASAR_CT_VAL_MASK              MSK_7
#define QUASAR_VTUNE_T_MASK             MSK_5

#define QUASAR_PLL_TUNE_ERR_OFFSET      17
#define QUASAR_PLL_VREG_D_OFFSET        16
#define QUASAR_PLL_VREG_EN_OFFSET       15
#define QUASAR_VCO_VREG_EN_OFFSET       14
#define QUASAR_VTUNE_RANGE_OFFSET       12
#define QUASAR_CT_VAL_OFFSET            5
#define QUASAR_VTUNE_T_OFFSET           0


//Quasar Register 4 Fields
#define QUASAR_VCO_SEL_MASK             MSK_1
#define QUASAR_CT_SETIME_MASK           MSK_1
#define QUASAR_THREE_FOURB_MASK         MSK_1
#define QUASAR_IBUF_BIAS_MASK           MSK_3
#define QUASAR_VCO_BIAS_MASK            MSK_3
#define QUASAR_CP_LOGIC_MASK            MSK_3
#define QUASAR_FRAC_OFFS_MASK           MSK_4
#define QUASAR_NDIV_BIAS_MASK           MSK_2

#define QUASAR_VCO_SEL_OFFSET           17
#define QUASAR_CT_SETIME_OFFSET         16
#define QUASAR_THREE_FOURB_OFFSET       15
#define QUASAR_IBUF_BIAS_OFFSET         12
#define QUASAR_VCO_BIAS_OFFSET          9
#define QUASAR_CP_LOGIC_OFFSET          6
#define QUASAR_FRAC_OFFS_OFFSET         2
#define QUASAR_NDIV_BIAS_OFFSET         0


//Quasar Register 5 Fields
#define QUASAR_LBW_CAL_SU_MASK          MSK_1
#define QUASAR_CP_GAIN_CAL_MASK         MSK_5
#define QUASAR_DELTA_NDIV_MASK          MSK_2
#define QUASAR_PLL_TRANGE_MASK          MSK_3
#define QUASAR_PLL_TGOAL_MASK           MSK_6
#define QUASAR_LOOP_CAL_EN_MASK         MSK_1

#define QUASAR_LBW_CAL_SU_OFFSET        17
#define QUASAR_CP_GAIN_CAL_OFFSET       12
#define QUASAR_DELTA_NDIV_OFFSET        10
#define QUASAR_PLL_TRANGE_OFFSET        7
#define QUASAR_PLL_TGOAL_OFFSET         1
#define QUASAR_LOOP_CAL_EN_OFFSET       0

//Quasar Register 6 Fields
#define QUASAR_EXT_IFLO_EN_MASK         MSK_1
#define QUASAR_IQ_DIV_EN_MASK           MSK_1
#define QUASAR_NDIV_LO_MASK             MSK_2
#define QUASAR_EXT_LO_MASK              MSK_2
#define QUASAR_TX1_LO_MASK              MSK_2
#define QUASAR_TX0_LO_MASK              MSK_2
#define QUASAR_RX2_LO_MASK              MSK_2
#define QUASAR_RX1_LO_MASK              MSK_2
#define QUASAR_RX0_LO_MASK              MSK_2

#define QUASAR_EXT_IFLO_EN_OFFSET       15
#define QUASAR_IQ_DIV_EN_OFFSET         14
#define QUASAR_NDIV_LO_OFFSET           12
#define QUASAR_EXT_LO_OFFSET            10
#define QUASAR_TX1_LO_OFFSET            8
#define QUASAR_TX0_LO_OFFSET            6
#define QUASAR_RX2_LO_OFFSET            4
#define QUASAR_RX1_LO_OFFSET            2
#define QUASAR_RX0_LO_OFFSET            0


//Quasar Register 7 Fields 2 2 3 3 2 1 1 3 1
#define QUASAR_MS_REV_MASK              MSK_2
#define QUASAR_XO_DISABLE_ST_MASK       MSK_2
#define QUASAR_RX1_ST_EN_MASK           MSK_3
#define QUASAR_RX_ALL_ST_EN_MASK        MSK_3
#define QUASAR_TX_ST_EN_MASK            MSK_2
#define QUASAR_PLL_EN_MASK              MSK_1
#define QUASAR_TXRX_BAND_MASK           MSK_1
#define QUASAR_MREV_MASK                MSK_3
#define QUASAR_TWOG_HS_EN_MASK          MSK_1

#define QUASAR_MS_REV_OFFSET            16
#define QUASAR_XO_DISABLE_ST_OFFSET     14
#define QUASAR_RX1_ST_EN_OFFSET         11
#define QUASAR_RX_ALL_ST_EN_OFFSET      8
#define QUASAR_TX_ST_EN_OFFSET          6
#define QUASAR_PLL_EN_OFFSET            5
#define QUASAR_TXRX_BAND_OFFSET         4
#define QUASAR_MREV_OFFSET              1
#define QUASAR_TWOG_HS_EN_OFFSET        0

//Quasar Register 8 Fields 6 6 6
#define QUASAR_RXG_2_MASK               MSK_6
#define QUASAR_RXG_1_MASK               MSK_6
#define QUASAR_RXG_0_MASK               MSK_6

#define QUASAR_RXG_2_OFFSET             12
#define QUASAR_RXG_1_OFFSET             6
#define QUASAR_RXG_0_OFFSET             0


//Quasar Register 9 Fields 2 1 1 6 4 4
#define QUASAR_GC_SELECT_MASK           MSK_1
#define QUASAR_SPI_LUT_EN_MASK          MSK_1
#define QUASAR_SPI_LUT_INDEX_MASK       MSK_6
#define QUASAR_TX_GAIN_0_MASK           MSK_4
#define QUASAR_TX_GAIN_1_MASK           MSK_4

#define QUASAR_GC_SELECT_OFFSET         15
#define QUASAR_SPI_LUT_EN_OFFSET        14
#define QUASAR_SPI_LUT_INDEX_OFFSET     8
#define QUASAR_TX_GAIN_0_OFFSET         4
#define QUASAR_TX_GAIN_1_OFFSET         0


//Quasar Register 10 Fields 4 7 7
#define QUASAR_RX_GAIN_2_MASK           MSK_7
#define QUASAR_RX_GAIN_1_MASK           MSK_7

#define QUASAR_RX_GAIN_2_OFFSET         7
#define QUASAR_RX_GAIN_1_OFFSET         0

//Quasar Register 11 Fields 11 7
#define QUASAR_RX_GAIN_0_MASK           MSK_7

#define QUASAR_RX_GAIN_0_OFFSET         0


//Quasar Register 12 Fields 2 2 7 7
#define QUASAR_RX0DC_RANGE_MASK         MSK_2
#define QUASAR_RX0DCI_MASK              MSK_7
#define QUASAR_RX0DCQ_MASK              MSK_7

#define QUASAR_RX0DC_RANGE_OFFSET       14
#define QUASAR_RX0DCI_OFFSET            7
#define QUASAR_RX0DCQ_OFFSET            0


//Quasar Register 13 Fields 2 2 7 7
#define QUASAR_RX1DC_RANGE_MASK         MSK_2
#define QUASAR_RX1DCI_MASK              MSK_7
#define QUASAR_RX1DCQ_MASK              MSK_7

#define QUASAR_RX1DC_RANGE_OFFSET       14
#define QUASAR_RX1DCI_OFFSET            7
#define QUASAR_RX1DCQ_OFFSET            0


//Quasar Register 14 Fields 2 2 7 7
#define QUASAR_RX2DC_RANGE_MASK         MSK_2
#define QUASAR_RX2DCI_MASK              MSK_7
#define QUASAR_RX2DCQ_MASK              MSK_7

#define QUASAR_RX2DC_RANGE_OFFSET       14
#define QUASAR_RX2DCI_OFFSET            7
#define QUASAR_RX2DCQ_OFFSET            0



//Quasar Register 15 Fields 1 1 1 3 1 1 2 1 1 5 1
#define QUASAR_CLIP_EN_0_MASK           MSK_1
#define QUASAR_CLIP_EN_1_MASK           MSK_1
#define QUASAR_CLIP_EN_2_MASK           MSK_1
#define QUASAR_MOD_INV_MASK             MSK_3
#define QUASAR_TX_RFLO_MASK             MSK_1
#define QUASAR_TX_IFLO_MASK             MSK_1
#define QUASAR_XO_DRV_MASK              MSK_2
#define QUASAR_XO_BYP_MASK              MSK_1
#define QUASAR_XO_BUF_EN_MASK           MSK_1
#define QUASAR_TOUT_MASK                MSK_5
#define QUASAR_TEN_MASK                 MSK_1

#define QUASAR_CLIP_EN_0_OFFSET         17
#define QUASAR_CLIP_EN_1_OFFSET         16
#define QUASAR_CLIP_EN_2_OFFSET         15
#define QUASAR_MOD_INV_OFFSET           12
#define QUASAR_TX_RFLO_OFFSET           11
#define QUASAR_TX_IFLO_OFFSET           10
#define QUASAR_XO_DRV_OFFSET            8
#define QUASAR_XO_BYP_OFFSET            7
#define QUASAR_XO_BUF_EN_OFFSET         6
#define QUASAR_TOUT_OFFSET              1
#define QUASAR_TEN_OFFSET               0



//Quasar Register 16 Fields 1 7 1 4 4 1
#define QUASAR_RC_ATUNE_VAL_MASK        MSK_7
#define QUASAR_RC_TUNE_EN_MASK          MSK_1
#define QUASAR_BBF_RX_TUNE_MASK         MSK_4
#define QUASAR_BBF_TX_TUNE_MASK         MSK_4
#define QUASAR_BBF_ATUNE_EN_MASK        MSK_1

#define QUASAR_RC_ATUNE_VAL_OFFSET      10
#define QUASAR_RC_TUNE_EN_OFFSET        9
#define QUASAR_BBF_RX_TUNE_OFFSET       5
#define QUASAR_BBF_TX_TUNE_OFFSET       1
#define QUASAR_BBF_ATUNE_EN_OFFSET      0


//Quasar Register 17 Fields 1 1 1 5 5 5
#define QUASAR_RX2_DCOC_EN_MASK         MSK_1
#define QUASAR_RX1_DCOC_EN_MASK         MSK_1
#define QUASAR_RX0_DCOC_EN_MASK         MSK_1
#define QUASAR_TX1_D_MASK               MSK_5
#define QUASAR_TX1D_D_MASK              MSK_5
#define QUASAR_RX1_D_MASK               MSK_5

#define QUASAR_RX2_DCOC_EN_OFFSET       17
#define QUASAR_RX1_DCOC_EN_OFFSET       16
#define QUASAR_RX0_DCOC_EN_OFFSET       15
#define QUASAR_TX1_D_OFFSET             10
#define QUASAR_TX1D_D_OFFSET            5
#define QUASAR_RX1_D_OFFSET             0


//Quasar Register 18 Fields 1 2 5 5 5
#define QUASAR_CLK_GATE_MASK            MSK_1
#define QUASAR_TX_DBIAS_MASK            MSK_2
#define QUASAR_TX0_D_MASK               MSK_5
#define QUASAR_TX0D_D_MASK              MSK_5
#define QUASAR_RX0_D_MASK               MSK_5

#define QUASAR_CLK_GATE_OFFSET          17
#define QUASAR_TX_DBIAS_OFFSET          15
#define QUASAR_TX0_D_OFFSET             10
#define QUASAR_TX0D_D_OFFSET            5
#define QUASAR_RX0_D_OFFSET             0


//Quasar Register 19 Fields 1 1 1 4 3 3 5
#define QUASAR_RX_IBIAS_EN_MASK         MSK_1
#define QUASAR_RX_RF_MIX_EN_MASK        MSK_1
#define QUASAR_RX_IF_MIX_EN_MASK        MSK_1
#define QUASAR_RX_IF_TUN_MASK           MSK_4
#define QUASAR_TX_RF_TUN_MASK           MSK_3
#define QUASAR_TX_IF_TUN_MASK           MSK_3
#define QUASAR_RX2_D_MASK               MSK_5

#define QUASAR_RX_IBIAS_EN_OFFSET       17
#define QUASAR_RX_RF_MIX_EN_OFFSET      16
#define QUASAR_RX_IF_MIX_EN_OFFSET      15
#define QUASAR_RX_IF_TUN_OFFSET         11
#define QUASAR_TX_RF_TUN_OFFSET         8
#define QUASAR_TX_IF_TUN_OFFSET         5
#define QUASAR_RX2_D_OFFSET             0


//Quasar Register 20 Fields 2 3 2 1 2 1 1 3 1 1 1
#define QUASAR_RX_CASC_GC_MASK          MSK_3
#define QUASAR_TX_CASC_GC_MASK          MSK_2
#define QUASAR_RX_IF_LODRV_EN_MASK      MSK_1
#define QUASAR_XO_GM_MASK               MSK_2
#define QUASAR_CLIP_TEST_MASK           MSK_1
#define QUASAR_CLIP_FREQ_MASK           MSK_1
#define QUASAR_CLIP_DET_TH_MASK         MSK_3
#define QUASAR_BBF_BIAS_MODE_MASK       MSK_1
#define QUASAR_TX_REG_MODE_MASK         MSK_1
#define QUASAR_TX_VREG_BYP_MASK         MSK_1

#define QUASAR_RX_CASC_GC_OFFSET          13
#define QUASAR_TX_CASC_GC_OFFSET          11
#define QUASAR_RX_IF_LODRV_EN_OFFSET      10
#define QUASAR_XO_GM_OFFSET               8
#define QUASAR_CLIP_TEST_OFFSET           7
#define QUASAR_CLIP_FREQ_OFFSET           6
#define QUASAR_CLIP_DET_TH_OFFSET         3
#define QUASAR_BBF_BIAS_MODE_OFFSET       2
#define QUASAR_TX_REG_MODE_OFFSET         1
#define QUASAR_TX_VREG_BYP_OFFSET         0


//Quasar Register 21 Fields 1 1 1 3 1 1 1 1 1 1 2 3 1
#define QUASAR_NDIV_OUT_MASK            MSK_1
#define QUASAR_RX_LB_GAIN_MASK          MSK_1
#define QUASAR_TX_LB_GAIN_MASK          MSK_1
#define QUASAR_TEST_LB_RF_MASK          MSK_3
#define QUASAR_RX_IQ_TEST_0_MASK        MSK_1
#define QUASAR_RX_IQ_TEST_1_MASK        MSK_1
#define QUASAR_RX_IQ_TEST_2_1_MASK      MSK_1
#define QUASAR_RX_IQ_TEST_2_0_MASK      MSK_1
#define QUASAR_TX_CAL_EN_0_MASK         MSK_1
#define QUASAR_TX_CAL_EN_1_MASK         MSK_1
#define QUASAR_DET_OFFSET_MASK          MSK_2
#define QUASAR_DET_GAIN_MASK            MSK_3
#define QUASAR_RDIV_TEST_MASK           MSK_1

#define QUASAR_NDIV_OUT_OFFSET          17
#define QUASAR_RX_LB_GAIN_OFFSET        16
#define QUASAR_TX_LB_GAIN_OFFSET        15
#define QUASAR_TEST_LB_RF_OFFSET        12
#define QUASAR_RX_IQ_TEST_0_OFFSET      11
#define QUASAR_RX_IQ_TEST_1_OFFSET      10
#define QUASAR_RX_IQ_TEST_2_1_OFFSET    9
#define QUASAR_RX_IQ_TEST_2_0_OFFSET    8
#define QUASAR_TX_CAL_EN_0_OFFSET       7
#define QUASAR_TX_CAL_EN_1_OFFSET       6
#define QUASAR_DET_OFFSET_OFFSET        4
#define QUASAR_DET_GAIN_OFFSET          1
#define QUASAR_RDIV_TEST_OFFSET         0


//Quasar Register 22 Fields 1 1 4 3 1 8
#define QUASAR_TX_DRVR_GAIN_MASK        MSK_1
#define QUASAR_TX_VGA_GAIN_MASK         MSK_4
#define QUASAR_TX_IQ_GAIN_MASK          MSK_3
#define QUASAR_TX_GTEST_MASK            MSK_1
#define QUASAR_BBF_IBIAS_CTL_MASK       MSK_8

#define QUASAR_TX_DRVR_GAIN_OFFSET      16
#define QUASAR_TX_VGA_GAIN_OFFSET       12
#define QUASAR_TX_IQ_GAIN_OFFSET        9
#define QUASAR_TX_GTEST_OFFSET          8
#define QUASAR_BBF_IBIAS_CTL_OFFSET     0


//Quasar Register 23 Fields 6 6 6
#define QUASAR_BBF_TEST_I_MASK          MSK_6
#define QUASAR_BBF_TEST_Q_MASK          MSK_6
#define QUASAR_CT_VAL_AUTO_MASK         MSK_6

#define QUASAR_BBF_TEST_I_OFFSET        12
#define QUASAR_BBF_TEST_Q_OFFSET        6
#define QUASAR_CT_VAL_AUTO_OFFSET       0


//Quasar Register 24 Fields 1 1 1 1 7 7
#define QUASAR_IO_TEST_MASK             MSK_1
#define QUASAR_TX_RF_EN_MASK            MSK_1
#define QUASAR_TX_DRVR_EN_MASK          MSK_1
#define QUASAR_TX_IQ_EN_MASK            MSK_1
#define QUASAR_BBF_ENQ_MASK             MSK_7
#define QUASAR_BBF_ENI_MASK             MSK_7

#define QUASAR_IO_TEST_OFFSET           17
#define QUASAR_TX_RF_EN_OFFSET          16
#define QUASAR_TX_DRVR_EN_OFFSET        15
#define QUASAR_TX_IQ_EN_OFFSET          14
#define QUASAR_BBF_ENQ_OFFSET           7
#define QUASAR_BBF_ENI_OFFSET           0


//Quasar Register 25 Fields 1 1 1 6 1 3 4 1
#define QUASAR_RX_GMTUNE_EN_MASK        MSK_1
#define QUASAR_XO_REG_BYP_MASK          MSK_1
#define QUASAR_XO_PLL_BUF_EN_MASK       MSK_1
#define QUASAR_ATEST_MASK               MSK_6
#define QUASAR_ATEST_EN_MASK            MSK_1
#define QUASAR_BBF_GAIN2_MASK           MSK_3
#define QUASAR_BBF_GAIN1_MASK           MSK_4
#define QUASAR_BBF_GAIN_TEST_MASK       MSK_1


#define QUASAR_RX_GMTUNE_EN_OFFSET      17
#define QUASAR_XO_REG_BYP_OFFSET        16
#define QUASAR_XO_PLL_BUF_EN_OFFSET     15
#define QUASAR_ATEST_OFFSET             9
#define QUASAR_ATEST_EN_OFFSET          8
#define QUASAR_BBF_GAIN2_OFFSET         5
#define QUASAR_BBF_GAIN1_OFFSET         1
#define QUASAR_BBF_GAIN_TEST_OFFSET     0


//Quasar Register 26 Fields
#define QUASAR_TX1_DCOC_EN_MASK         MSK_1
#define QUASAR_TX0_DCOC_EN_MASK         MSK_1
#define QUASAR_TX0_DCOC_I_MASK          MSK_5
#define QUASAR_TX0_DCOC_Q_MASK          MSK_5
#define QUASAR_ADC_TEST_MASK            MSK_5
#define QUASAR_ADC_TEST_EN_MASK         MSK_1

#define QUASAR_TX1_DCOC_EN_OFFSET       17
#define QUASAR_TX0_DCOC_EN_OFFSET       16
#define QUASAR_TX0_DCOC_I_OFFSET        11
#define QUASAR_TX0_DCOC_Q_OFFSET        6
#define QUASAR_ADC_TEST_OFFSET          1
#define QUASAR_ADC_TEST_EN_OFFSET       0


//Quasar Register 27
#define QUASAR_RX_MAINT_MASK            MSK_1
#define QUASAR_SPARES_MASK              MSK_7
#define QUASAR_TX1_DCOC_I_MASK          MSK_5
#define QUASAR_TX1_DCOC_Q_MASK          MSK_5

#define QUASAR_RX_MAINT_OFFSET          17
#define QUASAR_SPARES_OFFSET            10
#define QUASAR_TX1_DCOC_I_OFFSET        5
#define QUASAR_TX1_DCOC_Q_OFFSET        0


//Quasar Register 28
#define QUASAR_RESET_MASK               MSK_18

#define QUASAR_RESET_OFFSET             0


//Quasar Register 29
#define QUASAR_SPARES2_MASK               MSK_18

#define QUASAR_SPARES2_OFFSET             0






//other definitions
#define DCO_CORRECTION_RANGE      MSK_7






// Check on register fields vs. quasar.h
#if ((QUASAR_PLL1_NDIV_INT_MASK >> QUASAR_PLL1_NDIV_INT_OFFSET) !=  QUASAR_NDIV_INT_MASK)
#error QUASAR_PLL1_NDIV_INT_MASK not matching
#endif
#if (QUASAR_PLL1_NDIV_INT_OFFSET !=     QUASAR_NDIV_INT_OFFSET)
#error QUASAR_PLL1_NDIV_INT_OFFSET not matching
#endif


#if ((QUASAR_PLL1_NDIV_FRAC_MASK >> QUASAR_PLL1_NDIV_FRAC_OFFSET) !=    QUASAR_NDIV_FRAC_HI_MASK)
#error QUASAR_PLL1_NDIV_FRAC_MASK not matching
#endif
#if (QUASAR_PLL1_NDIV_FRAC_OFFSET !=    QUASAR_NDIV_FRAC_HI_OFFSET)
#error QUASAR_PLL1_NDIV_FRAC_OFFSET not matching
#endif


#if ((QUASAR_PLL1_CP_GAIN_MASK >> QUASAR_PLL1_CP_GAIN_OFFSET) !=    QUASAR_CP_GAIN_MASK)
#error QUASAR_PLL1_CP_GAIN_MASK not matching
#endif
#if (QUASAR_PLL1_CP_GAIN_OFFSET !=  QUASAR_CP_GAIN_OFFSET)
#error QUASAR_PLL1_CP_GAIN_OFFSET not matching
#endif


#if ((QUASAR_PLL1_NDIV_EN_MASK >> QUASAR_PLL1_NDIV_EN_OFFSET) !=    QUASAR_NDIV_EN_MASK)
#error QUASAR_PLL1_NDIV_EN_MASK not matching
#endif
#if (QUASAR_PLL1_NDIV_EN_OFFSET !=  QUASAR_NDIV_EN_OFFSET)
#error QUASAR_PLL1_NDIV_EN_OFFSET not matching
#endif


#if ((QUASAR_PLL1_PFD_EN_MASK >> QUASAR_PLL1_PFD_EN_OFFSET) !=  QUASAR_PFD_EN_MASK)
#error QUASAR_PLL1_PFD_EN_MASK not matching
#endif
#if (QUASAR_PLL1_PFD_EN_OFFSET !=   QUASAR_PFD_EN_OFFSET)
#error QUASAR_PLL1_PFD_EN_OFFSET not matching
#endif


#if ((QUASAR_PLL1_CP_EN_MASK >> QUASAR_PLL1_CP_EN_OFFSET) !=    QUASAR_CP_EN_MASK)
#error QUASAR_PLL1_CP_EN_MASK not matching
#endif
#if (QUASAR_PLL1_CP_EN_OFFSET !=    QUASAR_CP_EN_OFFSET)
#error QUASAR_PLL1_CP_EN_OFFSET not matching
#endif


#if ((QUASAR_PLL1_FNZ_MASK >> QUASAR_PLL1_FNZ_OFFSET) !=    QUASAR_FNZ_MASK)
#error QUASAR_PLL1_FNZ_MASK not matching
#endif
#if (QUASAR_PLL1_FNZ_OFFSET !=  QUASAR_FNZ_OFFSET)
#error QUASAR_PLL1_FNZ_OFFSET not matching
#endif


#if ((QUASAR_PLL2_NDIV_FRAC_MASK >> QUASAR_PLL2_NDIV_FRAC_OFFSET) !=    QUASAR_NDIV_FRAC_LO_MASK)
#error QUASAR_PLL2_NDIV_FRAC_MASK not matching
#endif
#if (QUASAR_PLL2_NDIV_FRAC_OFFSET !=    QUASAR_NDIV_FRAC_LO_OFFSET)
#error QUASAR_PLL2_NDIV_FRAC_OFFSET not matching
#endif


#if ((QUASAR_PLL3_PLL_CT_ACTIVE_MASK >> QUASAR_PLL3_PLL_CT_ACTIVE_OFFSET) !=    QUASAR_PLL_CT_ACTIVE_MASK)
#error QUASAR_PLL3_PLL_CT_ACTIVE_MASK not matching
#endif
#if (QUASAR_PLL3_PLL_CT_ACTIVE_OFFSET !=    QUASAR_PLL_CT_ACTIVE_OFFSET)
#error QUASAR_PLL3_PLL_CT_ACTIVE_OFFSET not matching
#endif


#if ((QUASAR_PLL3_VCO_EN_MASK >> QUASAR_PLL3_VCO_EN_OFFSET) !=  QUASAR_VCO_EN_MASK   )
#error QUASAR_PLL3_VCO_EN_MASK not matching
#endif
#if (QUASAR_PLL3_VCO_EN_OFFSET !=   QUASAR_VCO_EN_OFFSET )
#error QUASAR_PLL3_VCO_EN_OFFSET not matching
#endif


#if ((QUASAR_PLL3_CT_EN_MASK >> QUASAR_PLL3_CT_EN_OFFSET) !=    QUASAR_CT_EN_MASK  )
#error QUASAR_PLL3_CT_EN_MASK not matching
#endif
#if (QUASAR_PLL3_CT_EN_OFFSET !=    QUASAR_CT_EN_OFFSET)
#error QUASAR_PLL3_CT_EN_OFFSET not matching
#endif


#if ((QUASAR_PLL3_RDIV_MASK >> QUASAR_PLL3_RDIV_OFFSET) !=  QUASAR_RDIV_MASK  )
#error QUASAR_PLL3_RDIV_MASK not matching
#endif
#if (QUASAR_PLL3_RDIV_OFFSET !=     QUASAR_RDIV_OFFSET)
#error QUASAR_PLL3_RDIV_OFFSET not matching
#endif


#if ((QUASAR_PLL3_EXT_RFLO_EN_MASK >> QUASAR_PLL3_EXT_RFLO_EN_OFFSET) !=    QUASAR_EXT_RFLO_EN_MASK  )
#error QUASAR_PLL3_EXT_RFLO_EN_MASK not matching
#endif
#if (QUASAR_PLL3_EXT_RFLO_EN_OFFSET !=  QUASAR_EXT_RFLO_EN_OFFSET)
#error QUASAR_PLL3_EXT_RFLO_EN_OFFSET not matching
#endif


#if ((QUASAR_PLL3_RFLO_OUT_EN_MASK >> QUASAR_PLL3_RFLO_OUT_EN_OFFSET) !=    QUASAR_RFLO_OUT_EN_MASK  )
#error QUASAR_PLL3_RFLO_OUT_EN_MASK not matching
#endif
#if (QUASAR_PLL3_RFLO_OUT_EN_OFFSET !=  QUASAR_RFLO_OUT_EN_OFFSET)
#error QUASAR_PLL3_RFLO_OUT_EN_OFFSET not matching
#endif


#if ((QUASAR_PLL3_PLL_CT_START_MASK >> QUASAR_PLL3_PLL_CT_START_OFFSET) !=  QUASAR_PLL_CT_START_MASK  )
#error QUASAR_PLL3_PLL_CT_START_MASK not matching
#endif
#if (QUASAR_PLL3_PLL_CT_START_OFFSET !=     QUASAR_PLL_CT_START_OFFSET)
#error QUASAR_PLL3_PLL_CT_START_OFFSET not matching
#endif


#if ((QUASAR_PLL3_PLL_ADC_AQ_MASK >> QUASAR_PLL3_PLL_ADC_AQ_OFFSET) !=  QUASAR_PLL_ADC_AQ_MASK  )
#error QUASAR_PLL3_PLL_ADC_AQ_MASK not matching
#endif
#if (QUASAR_PLL3_PLL_ADC_AQ_OFFSET !=   QUASAR_PLL_ADC_AQ_OFFSET)
#error QUASAR_PLL3_PLL_ADC_AQ_OFFSET not matching
#endif


#if ((QUASAR_PLL3_VTUNE_VAL_MASK >> QUASAR_PLL3_VTUNE_VAL_OFFSET) !=    QUASAR_VTUNE_VAL_MASK  )
#error QUASAR_PLL3_VTUNE_VAL_MASK not matching
#endif
#if (QUASAR_PLL3_VTUNE_VAL_OFFSET !=    QUASAR_VTUNE_VAL_OFFSET)
#error QUASAR_PLL3_VTUNE_VAL_OFFSET not matching
#endif


#if ((QUASAR_PLL3_CT_MAINT_MASK >> QUASAR_PLL3_CT_MAINT_OFFSET) !=  QUASAR_CT_MAINT_MASK  )
#error QUASAR_PLL3_CT_MAINT_MASK not matching
#endif
#if (QUASAR_PLL3_CT_MAINT_OFFSET !=     QUASAR_CT_MAINT_OFFSET)
#error QUASAR_PLL3_CT_MAINT_OFFSET not matching
#endif


#if ((QUASAR_PLL4_PLL_TUNE_ERR_MASK >> QUASAR_PLL4_PLL_TUNE_ERR_OFFSET) !=  QUASAR_PLL_TUNE_ERR_MASK  )
#error QUASAR_PLL4_PLL_TUNE_ERR_MASK not matching
#endif
#if (QUASAR_PLL4_PLL_TUNE_ERR_OFFSET !=     QUASAR_PLL_TUNE_ERR_OFFSET)
#error QUASAR_PLL4_PLL_TUNE_ERR_OFFSET not matching
#endif


#if ((QUASAR_PLL4_PLL_VREG_D_MASK >> QUASAR_PLL4_PLL_VREG_D_OFFSET) !=  QUASAR_PLL_VREG_D_MASK  )
#error QUASAR_PLL4_PLL_VREG_D_MASK not matching
#endif
#if (QUASAR_PLL4_PLL_VREG_D_OFFSET !=   QUASAR_PLL_VREG_D_OFFSET)
#error QUASAR_PLL4_PLL_VREG_D_OFFSET not matching
#endif


#if ((QUASAR_PLL4_PLL_VREG_EN_MASK >> QUASAR_PLL4_PLL_VREG_EN_OFFSET) !=    QUASAR_PLL_VREG_EN_MASK  )
#error QUASAR_PLL4_PLL_VREG_EN_MASK not matching
#endif
#if (QUASAR_PLL4_PLL_VREG_EN_OFFSET !=  QUASAR_PLL_VREG_EN_OFFSET)
#error QUASAR_PLL4_PLL_VREG_EN_OFFSET not matching
#endif


#if ((QUASAR_PLL4_VCO_VREG_EN_MASK >> QUASAR_PLL4_VCO_VREG_EN_OFFSET) !=    QUASAR_VCO_VREG_EN_MASK  )
#error QUASAR_PLL4_VCO_VREG_EN_MASK not matching
#endif
#if (QUASAR_PLL4_VCO_VREG_EN_OFFSET !=  QUASAR_VCO_VREG_EN_OFFSET)
#error QUASAR_PLL4_VCO_VREG_EN_OFFSET not matching
#endif


#if ((QUASAR_PLL4_VTUNE_RANGE_MASK >> QUASAR_PLL4_VTUNE_RANGE_OFFSET) !=    QUASAR_VTUNE_RANGE_MASK  )
#error QUASAR_PLL4_VTUNE_RANGE_MASK not matching
#endif
#if (QUASAR_PLL4_VTUNE_RANGE_OFFSET !=  QUASAR_VTUNE_RANGE_OFFSET)
#error QUASAR_PLL4_VTUNE_RANGE_OFFSET not matching
#endif


#if ((QUASAR_PLL4_CT_VAL_MASK >> QUASAR_PLL4_CT_VAL_OFFSET) !=  QUASAR_CT_VAL_MASK  )
#error QUASAR_PLL4_CT_VAL_MASK not matching
#endif
#if (QUASAR_PLL4_CT_VAL_OFFSET !=   QUASAR_CT_VAL_OFFSET)
#error QUASAR_PLL4_CT_VAL_OFFSET not matching
#endif


#if ((QUASAR_PLL4_VTUNE_T_MASK >> QUASAR_PLL4_VTUNE_T_OFFSET) !=    QUASAR_VTUNE_T_MASK  )
#error QUASAR_PLL4_VTUNE_T_MASK not matching
#endif
#if (QUASAR_PLL4_VTUNE_T_OFFSET !=  QUASAR_VTUNE_T_OFFSET)
#error QUASAR_PLL4_VTUNE_T_OFFSET not matching
#endif


#if ((QUASAR_PLL5_VCO_SEL_MASK >> QUASAR_PLL5_VCO_SEL_OFFSET) !=    QUASAR_VCO_SEL_MASK  )
#error QUASAR_PLL5_VCO_SEL_MASK not matching
#endif
#if (QUASAR_PLL5_VCO_SEL_OFFSET !=  QUASAR_VCO_SEL_OFFSET)
#error QUASAR_PLL5_VCO_SEL_OFFSET not matching
#endif


#if ((QUASAR_PLL5_CT_SETIME_MASK >> QUASAR_PLL5_CT_SETIME_OFFSET) !=    QUASAR_CT_SETIME_MASK  )
#error QUASAR_PLL5_CT_SETIME_MASK not matching
#endif
#if (QUASAR_PLL5_CT_SETIME_OFFSET !=    QUASAR_CT_SETIME_OFFSET)
#error QUASAR_PLL5_CT_SETIME_OFFSET not matching
#endif


#if ((QUASAR_PLL5_THREE_FOURB_MASK >> QUASAR_PLL5_THREE_FOURB_OFFSET) !=    QUASAR_THREE_FOURB_MASK  )
#error QUASAR_PLL5_THREE_FOURB_MASK not matching
#endif
#if (QUASAR_PLL5_THREE_FOURB_OFFSET !=  QUASAR_THREE_FOURB_OFFSET)
#error QUASAR_PLL5_THREE_FOURB_OFFSET not matching
#endif


#if ((QUASAR_PLL5_IBUF_BIAS_MASK >> QUASAR_PLL5_IBUF_BIAS_OFFSET) !=    QUASAR_IBUF_BIAS_MASK  )
#error QUASAR_PLL5_IBUF_BIAS_MASK not matching
#endif
#if (QUASAR_PLL5_IBUF_BIAS_OFFSET !=    QUASAR_IBUF_BIAS_OFFSET)
#error QUASAR_PLL5_IBUF_BIAS_OFFSET not matching
#endif


#if ((QUASAR_PLL5_VCO_BIAS_MASK >> QUASAR_PLL5_VCO_BIAS_OFFSET) !=  QUASAR_VCO_BIAS_MASK  )
#error QUASAR_PLL5_VCO_BIAS_MASK not matching
#endif
#if (QUASAR_PLL5_VCO_BIAS_OFFSET !=     QUASAR_VCO_BIAS_OFFSET)
#error QUASAR_PLL5_VCO_BIAS_OFFSET not matching
#endif


#if ((QUASAR_PLL5_CP_LOGIC_MASK >> QUASAR_PLL5_CP_LOGIC_OFFSET) !=  QUASAR_CP_LOGIC_MASK  )
#error QUASAR_PLL5_CP_LOGIC_MASK not matching
#endif
#if (QUASAR_PLL5_CP_LOGIC_OFFSET !=     QUASAR_CP_LOGIC_OFFSET)
#error QUASAR_PLL5_CP_LOGIC_OFFSET not matching
#endif


#if ((QUASAR_PLL5_FRAC_OFFS_MASK >> QUASAR_PLL5_FRAC_OFFS_OFFSET) !=    QUASAR_FRAC_OFFS_MASK  )
#error QUASAR_PLL5_FRAC_OFFS_MASK not matching
#endif
#if (QUASAR_PLL5_FRAC_OFFS_OFFSET !=    QUASAR_FRAC_OFFS_OFFSET)
#error QUASAR_PLL5_FRAC_OFFS_OFFSET not matching
#endif


#if ((QUASAR_PLL5_NDIV_BIAS_MASK >> QUASAR_PLL5_NDIV_BIAS_OFFSET) !=    QUASAR_NDIV_BIAS_MASK  )
#error QUASAR_PLL5_NDIV_BIAS_MASK not matching
#endif
#if (QUASAR_PLL5_NDIV_BIAS_OFFSET !=    QUASAR_NDIV_BIAS_OFFSET)
#error QUASAR_PLL5_NDIV_BIAS_OFFSET not matching
#endif


#if ((QUASAR_PLL6_LBW_CAL_SU_MASK >> QUASAR_PLL6_LBW_CAL_SU_OFFSET) !=  QUASAR_LBW_CAL_SU_MASK  )
#error QUASAR_PLL6_LBW_CAL_SU_MASK not matching
#endif
#if (QUASAR_PLL6_LBW_CAL_SU_OFFSET !=   QUASAR_LBW_CAL_SU_OFFSET)
#error QUASAR_PLL6_LBW_CAL_SU_OFFSET not matching
#endif


#if ((QUASAR_PLL6_CP_GAIN_CAL_MASK >> QUASAR_PLL6_CP_GAIN_CAL_OFFSET) !=    QUASAR_CP_GAIN_CAL_MASK  )
#error QUASAR_PLL6_CP_GAIN_CAL_MASK not matching
#endif
#if (QUASAR_PLL6_CP_GAIN_CAL_OFFSET !=  QUASAR_CP_GAIN_CAL_OFFSET)
#error QUASAR_PLL6_CP_GAIN_CAL_OFFSET not matching
#endif


#if ((QUASAR_PLL6_DELTA_NDIV_MASK >> QUASAR_PLL6_DELTA_NDIV_OFFSET) !=  QUASAR_DELTA_NDIV_MASK  )
#error QUASAR_PLL6_DELTA_NDIV_MASK not matching
#endif
#if (QUASAR_PLL6_DELTA_NDIV_OFFSET !=   QUASAR_DELTA_NDIV_OFFSET)
#error QUASAR_PLL6_DELTA_NDIV_OFFSET not matching
#endif


#if ((QUASAR_PLL6_PLL_TRANGE_MASK >> QUASAR_PLL6_PLL_TRANGE_OFFSET) !=  QUASAR_PLL_TRANGE_MASK  )
#error QUASAR_PLL6_PLL_TRANGE_MASK not matching
#endif
#if (QUASAR_PLL6_PLL_TRANGE_OFFSET !=   QUASAR_PLL_TRANGE_OFFSET)
#error QUASAR_PLL6_PLL_TRANGE_OFFSET not matching
#endif


#if ((QUASAR_PLL6_PLL_TGOAL_MASK >> QUASAR_PLL6_PLL_TGOAL_OFFSET) !=    QUASAR_PLL_TGOAL_MASK  )
#error QUASAR_PLL6_PLL_TGOAL_MASK not matching
#endif
#if (QUASAR_PLL6_PLL_TGOAL_OFFSET !=    QUASAR_PLL_TGOAL_OFFSET)
#error QUASAR_PLL6_PLL_TGOAL_OFFSET not matching
#endif


#if ((QUASAR_PLL6_LOOP_CAL_EN_MASK >> QUASAR_PLL6_LOOP_CAL_EN_OFFSET) !=    QUASAR_LOOP_CAL_EN_MASK  )
#error QUASAR_PLL6_LOOP_CAL_EN_MASK not matching
#endif
#if (QUASAR_PLL6_LOOP_CAL_EN_OFFSET !=  QUASAR_LOOP_CAL_EN_OFFSET)
#error QUASAR_PLL6_LOOP_CAL_EN_OFFSET not matching
#endif


#if ((QUASAR_LO_CONFIG_EXT_IFLO_EN_MASK >> QUASAR_LO_CONFIG_EXT_IFLO_EN_OFFSET) !=  QUASAR_EXT_IFLO_EN_MASK  )
#error QUASAR_LO_CONFIG_EXT_IFLO_EN_MASK not matching
#endif
#if (QUASAR_LO_CONFIG_EXT_IFLO_EN_OFFSET !=     QUASAR_EXT_IFLO_EN_OFFSET)
#error QUASAR_LO_CONFIG_EXT_IFLO_EN_OFFSET not matching
#endif


#if ((QUASAR_LO_CONFIG_IQ_DIV_EN_MASK >> QUASAR_LO_CONFIG_IQ_DIV_EN_OFFSET) !=  QUASAR_IQ_DIV_EN_MASK  )
#error QUASAR_LO_CONFIG_IQ_DIV_EN_MASK not matching
#endif
#if (QUASAR_LO_CONFIG_IQ_DIV_EN_OFFSET !=   QUASAR_IQ_DIV_EN_OFFSET)
#error QUASAR_LO_CONFIG_IQ_DIV_EN_OFFSET not matching
#endif


#if ((QUASAR_LO_CONFIG_NDIV_LO_MASK >> QUASAR_LO_CONFIG_NDIV_LO_OFFSET) !=  QUASAR_NDIV_LO_MASK  )
#error QUASAR_LO_CONFIG_NDIV_LO_MASK not matching
#endif
#if (QUASAR_LO_CONFIG_NDIV_LO_OFFSET !=     QUASAR_NDIV_LO_OFFSET)
#error QUASAR_LO_CONFIG_NDIV_LO_OFFSET not matching
#endif


#if ((QUASAR_LO_CONFIG_EXT_LO_MASK >> QUASAR_LO_CONFIG_EXT_LO_OFFSET) !=    QUASAR_EXT_LO_MASK  )
#error QUASAR_LO_CONFIG_EXT_LO_MASK not matching
#endif
#if (QUASAR_LO_CONFIG_EXT_LO_OFFSET !=  QUASAR_EXT_LO_OFFSET)
#error QUASAR_LO_CONFIG_EXT_LO_OFFSET not matching
#endif


#if ((QUASAR_LO_CONFIG_TX1_LO_MASK >> QUASAR_LO_CONFIG_TX1_LO_OFFSET) !=    QUASAR_TX1_LO_MASK  )
#error QUASAR_LO_CONFIG_TX1_LO_MASK not matching
#endif
#if (QUASAR_LO_CONFIG_TX1_LO_OFFSET !=  QUASAR_TX1_LO_OFFSET)
#error QUASAR_LO_CONFIG_TX1_LO_OFFSET not matching
#endif


#if ((QUASAR_LO_CONFIG_TX0_LO_MASK >> QUASAR_LO_CONFIG_TX0_LO_OFFSET) !=    QUASAR_TX0_LO_MASK  )
#error QUASAR_LO_CONFIG_TX0_LO_MASK not matching
#endif
#if (QUASAR_LO_CONFIG_TX0_LO_OFFSET !=  QUASAR_TX0_LO_OFFSET)
#error QUASAR_LO_CONFIG_TX0_LO_OFFSET not matching
#endif


#if ((QUASAR_LO_CONFIG_RX2_LO_MASK >> QUASAR_LO_CONFIG_RX2_LO_OFFSET) !=    QUASAR_RX2_LO_MASK  )
#error QUASAR_LO_CONFIG_RX2_LO_MASK not matching
#endif
#if (QUASAR_LO_CONFIG_RX2_LO_OFFSET !=  QUASAR_RX2_LO_OFFSET)
#error QUASAR_LO_CONFIG_RX2_LO_OFFSET not matching
#endif


#if ((QUASAR_LO_CONFIG_RX1_LO_MASK >> QUASAR_LO_CONFIG_RX1_LO_OFFSET) !=    QUASAR_RX1_LO_MASK  )
#error QUASAR_LO_CONFIG_RX1_LO_MASK not matching
#endif
#if (QUASAR_LO_CONFIG_RX1_LO_OFFSET !=  QUASAR_RX1_LO_OFFSET)
#error QUASAR_LO_CONFIG_RX1_LO_OFFSET not matching
#endif


#if ((QUASAR_LO_CONFIG_RX0_LO_MASK >> QUASAR_LO_CONFIG_RX0_LO_OFFSET) !=    QUASAR_RX0_LO_MASK  )
#error QUASAR_LO_CONFIG_RX0_LO_MASK not matching
#endif
#if (QUASAR_LO_CONFIG_RX0_LO_OFFSET !=  QUASAR_RX0_LO_OFFSET)
#error QUASAR_LO_CONFIG_RX0_LO_OFFSET not matching
#endif


#if ((QUASAR_STATE_MS_REV_MASK >> QUASAR_STATE_MS_REV_OFFSET) !=    QUASAR_MS_REV_MASK  )
#error QUASAR_STATE_MS_REV_MASK not matching
#endif
#if (QUASAR_STATE_MS_REV_OFFSET !=  QUASAR_MS_REV_OFFSET)
#error QUASAR_STATE_MS_REV_OFFSET not matching
#endif


#if ((QUASAR_STATE_XO_DISABLE_ST_MASK >> QUASAR_STATE_XO_DISABLE_ST_OFFSET) !=  QUASAR_XO_DISABLE_ST_MASK  )
#error QUASAR_STATE_XO_DISABLE_ST_MASK not matching
#endif
#if (QUASAR_STATE_XO_DISABLE_ST_OFFSET !=   QUASAR_XO_DISABLE_ST_OFFSET)
#error QUASAR_STATE_XO_DISABLE_ST_OFFSET not matching
#endif


#if ((QUASAR_STATE_RX1_ST_EN_MASK >> QUASAR_STATE_RX1_ST_EN_OFFSET) !=  QUASAR_RX1_ST_EN_MASK  )
#error QUASAR_STATE_RX1_ST_EN_MASK not matching
#endif
#if (QUASAR_STATE_RX1_ST_EN_OFFSET !=   QUASAR_RX1_ST_EN_OFFSET)
#error QUASAR_STATE_RX1_ST_EN_OFFSET not matching
#endif


#if ((QUASAR_STATE_RX_ALL_ST_EN_MASK >> QUASAR_STATE_RX_ALL_ST_EN_OFFSET) !=    QUASAR_RX_ALL_ST_EN_MASK  )
#error QUASAR_STATE_RX_ALL_ST_EN_MASK not matching
#endif
#if (QUASAR_STATE_RX_ALL_ST_EN_OFFSET !=    QUASAR_RX_ALL_ST_EN_OFFSET)
#error QUASAR_STATE_RX_ALL_ST_EN_OFFSET not matching
#endif


#if ((QUASAR_STATE_TX_ST_EN_MASK >> QUASAR_STATE_TX_ST_EN_OFFSET) !=    QUASAR_TX_ST_EN_MASK  )
#error QUASAR_STATE_TX_ST_EN_MASK not matching
#endif
#if (QUASAR_STATE_TX_ST_EN_OFFSET !=    QUASAR_TX_ST_EN_OFFSET)
#error QUASAR_STATE_TX_ST_EN_OFFSET not matching
#endif


#if ((QUASAR_STATE_PLL_EN_MASK >> QUASAR_STATE_PLL_EN_OFFSET) !=    QUASAR_PLL_EN_MASK  )
#error QUASAR_STATE_PLL_EN_MASK not matching
#endif
#if (QUASAR_STATE_PLL_EN_OFFSET !=  QUASAR_PLL_EN_OFFSET)
#error QUASAR_STATE_PLL_EN_OFFSET not matching
#endif


#if ((QUASAR_STATE_TXRX_BAND_MASK >> QUASAR_STATE_TXRX_BAND_OFFSET) !=  QUASAR_TXRX_BAND_MASK  )
#error QUASAR_STATE_TXRX_BAND_MASK not matching
#endif
#if (QUASAR_STATE_TXRX_BAND_OFFSET !=   QUASAR_TXRX_BAND_OFFSET)
#error QUASAR_STATE_TXRX_BAND_OFFSET not matching
#endif


#if ((QUASAR_STATE_MREV_MASK >> QUASAR_STATE_MREV_OFFSET) !=    QUASAR_MREV_MASK  )
#error QUASAR_STATE_MREV_MASK not matching
#endif
#if (QUASAR_STATE_MREV_OFFSET !=    QUASAR_MREV_OFFSET)
#error QUASAR_STATE_MREV_OFFSET not matching
#endif


#if ((QUASAR_STATE_TWOG_HS_EN_MASK >> QUASAR_STATE_TWOG_HS_EN_OFFSET) !=    QUASAR_TWOG_HS_EN_MASK  )
#error QUASAR_STATE_TWOG_HS_EN_MASK not matching
#endif
#if (QUASAR_STATE_TWOG_HS_EN_OFFSET !=  QUASAR_TWOG_HS_EN_OFFSET)
#error QUASAR_STATE_TWOG_HS_EN_OFFSET not matching
#endif


#if ((QUASAR_GC1_RXG_2_MASK >> QUASAR_GC1_RXG_2_OFFSET) !=  QUASAR_RXG_2_MASK  )
#error QUASAR_GC1_RXG_2_MASK not matching
#endif
#if (QUASAR_GC1_RXG_2_OFFSET !=     QUASAR_RXG_2_OFFSET)
#error QUASAR_GC1_RXG_2_OFFSET not matching
#endif


#if ((QUASAR_GC1_RXG_1_MASK >> QUASAR_GC1_RXG_1_OFFSET) !=  QUASAR_RXG_1_MASK  )
#error QUASAR_GC1_RXG_1_MASK not matching
#endif
#if (QUASAR_GC1_RXG_1_OFFSET !=     QUASAR_RXG_1_OFFSET)
#error QUASAR_GC1_RXG_1_OFFSET not matching
#endif


#if ((QUASAR_GC1_RXG_0_MASK >> QUASAR_GC1_RXG_0_OFFSET) !=  QUASAR_RXG_0_MASK  )
#error QUASAR_GC1_RXG_0_MASK not matching
#endif
#if (QUASAR_GC1_RXG_0_OFFSET !=     QUASAR_RXG_0_OFFSET)
#error QUASAR_GC1_RXG_0_OFFSET not matching
#endif


#if ((QUASAR_GC2_GC_SELECT_MASK >> QUASAR_GC2_GC_SELECT_OFFSET) !=  QUASAR_GC_SELECT_MASK  )
#error QUASAR_GC2_GC_SELECT_MASK not matching
#endif
#if (QUASAR_GC2_GC_SELECT_OFFSET !=     QUASAR_GC_SELECT_OFFSET)
#error QUASAR_GC2_GC_SELECT_OFFSET not matching
#endif


#if ((QUASAR_GC2_SPI_LUT_EN_MASK >> QUASAR_GC2_SPI_LUT_EN_OFFSET) !=    QUASAR_SPI_LUT_EN_MASK  )
#error QUASAR_GC2_SPI_LUT_EN_MASK not matching
#endif
#if (QUASAR_GC2_SPI_LUT_EN_OFFSET !=    QUASAR_SPI_LUT_EN_OFFSET)
#error QUASAR_GC2_SPI_LUT_EN_OFFSET not matching
#endif


#if ((QUASAR_GC2_SPI_LUT_INDEX_MASK >> QUASAR_GC2_SPI_LUT_INDEX_OFFSET) !=  QUASAR_SPI_LUT_INDEX_MASK  )
#error QUASAR_GC2_SPI_LUT_INDEX_MASK not matching
#endif
#if (QUASAR_GC2_SPI_LUT_INDEX_OFFSET !=     QUASAR_SPI_LUT_INDEX_OFFSET)
#error QUASAR_GC2_SPI_LUT_INDEX_OFFSET not matching
#endif


#if ((QUASAR_GC2_TX_GAIN_0_MASK >> QUASAR_GC2_TX_GAIN_0_OFFSET) !=  QUASAR_TX_GAIN_0_MASK  )
#error QUASAR_GC2_TX_GAIN_0_MASK not matching
#endif
#if (QUASAR_GC2_TX_GAIN_0_OFFSET !=     QUASAR_TX_GAIN_0_OFFSET)
#error QUASAR_GC2_TX_GAIN_0_OFFSET not matching
#endif


#if ((QUASAR_GC2_TX_GAIN_1_MASK >> QUASAR_GC2_TX_GAIN_1_OFFSET) !=  QUASAR_TX_GAIN_1_MASK  )
#error QUASAR_GC2_TX_GAIN_1_MASK not matching
#endif
#if (QUASAR_GC2_TX_GAIN_1_OFFSET !=     QUASAR_TX_GAIN_1_OFFSET)
#error QUASAR_GC2_TX_GAIN_1_OFFSET not matching
#endif


#if ((QUASAR_GC3_RX_GAIN_2_MASK >> QUASAR_GC3_RX_GAIN_2_OFFSET) !=  QUASAR_RX_GAIN_2_MASK  )
#error QUASAR_GC3_RX_GAIN_2_MASK not matching
#endif
#if (QUASAR_GC3_RX_GAIN_2_OFFSET !=     QUASAR_RX_GAIN_2_OFFSET)
#error QUASAR_GC3_RX_GAIN_2_OFFSET not matching
#endif


#if ((QUASAR_GC3_RX_GAIN_1_MASK >> QUASAR_GC3_RX_GAIN_1_OFFSET) !=  QUASAR_RX_GAIN_1_MASK  )
#error QUASAR_GC3_RX_GAIN_1_MASK not matching
#endif
#if (QUASAR_GC3_RX_GAIN_1_OFFSET !=     QUASAR_RX_GAIN_1_OFFSET)
#error QUASAR_GC3_RX_GAIN_1_OFFSET not matching
#endif


#if ((QUASAR_GC4_RX_GAIN_0_MASK >> QUASAR_GC4_RX_GAIN_0_OFFSET) !=  QUASAR_RX_GAIN_0_MASK  )
#error QUASAR_GC4_RX_GAIN_0_MASK not matching
#endif
#if (QUASAR_GC4_RX_GAIN_0_OFFSET !=     QUASAR_RX_GAIN_0_OFFSET)
#error QUASAR_GC4_RX_GAIN_0_OFFSET not matching
#endif


#if ((QUASAR_DCOC0_RX0DC_RANGE_MASK >> QUASAR_DCOC0_RX0DC_RANGE_OFFSET) !=  QUASAR_RX0DC_RANGE_MASK  )
#error QUASAR_DCOC0_RX0DC_RANGE_MASK not matching
#endif
#if (QUASAR_DCOC0_RX0DC_RANGE_OFFSET !=     QUASAR_RX0DC_RANGE_OFFSET)
#error QUASAR_DCOC0_RX0DC_RANGE_OFFSET not matching
#endif


#if ((QUASAR_DCOC0_RX0DCI_MASK >> QUASAR_DCOC0_RX0DCI_OFFSET) !=    QUASAR_RX0DCI_MASK  )
#error QUASAR_DCOC0_RX0DCI_MASK not matching
#endif
#if (QUASAR_DCOC0_RX0DCI_OFFSET !=  QUASAR_RX0DCI_OFFSET)
#error QUASAR_DCOC0_RX0DCI_OFFSET not matching
#endif


#if ((QUASAR_DCOC0_RX0DCQ_MASK >> QUASAR_DCOC0_RX0DCQ_OFFSET) !=    QUASAR_RX0DCQ_MASK  )
#error QUASAR_DCOC0_RX0DCQ_MASK not matching
#endif
#if (QUASAR_DCOC0_RX0DCQ_OFFSET !=  QUASAR_RX0DCQ_OFFSET)
#error QUASAR_DCOC0_RX0DCQ_OFFSET not matching
#endif


#if ((QUASAR_DCOC1_RX1DC_RANGE_MASK >> QUASAR_DCOC1_RX1DC_RANGE_OFFSET) !=  QUASAR_RX1DC_RANGE_MASK  )
#error QUASAR_DCOC1_RX1DC_RANGE_MASK not matching
#endif
#if (QUASAR_DCOC1_RX1DC_RANGE_OFFSET !=     QUASAR_RX1DC_RANGE_OFFSET)
#error QUASAR_DCOC1_RX1DC_RANGE_OFFSET not matching
#endif


#if ((QUASAR_DCOC1_RX1DCI_MASK >> QUASAR_DCOC1_RX1DCI_OFFSET) !=    QUASAR_RX1DCI_MASK  )
#error QUASAR_DCOC1_RX1DCI_MASK not matching
#endif
#if (QUASAR_DCOC1_RX1DCI_OFFSET !=  QUASAR_RX1DCI_OFFSET)
#error QUASAR_DCOC1_RX1DCI_OFFSET not matching
#endif


#if ((QUASAR_DCOC1_RX1DCQ_MASK >> QUASAR_DCOC1_RX1DCQ_OFFSET) !=    QUASAR_RX1DCQ_MASK  )
#error QUASAR_DCOC1_RX1DCQ_MASK not matching
#endif
#if (QUASAR_DCOC1_RX1DCQ_OFFSET !=  QUASAR_RX1DCQ_OFFSET)
#error QUASAR_DCOC1_RX1DCQ_OFFSET not matching
#endif


#if ((QUASAR_DCOC2_RX2DC_RANGE_MASK >> QUASAR_DCOC2_RX2DC_RANGE_OFFSET) !=  QUASAR_RX2DC_RANGE_MASK  )
#error QUASAR_DCOC2_RX2DC_RANGE_MASK not matching
#endif
#if (QUASAR_DCOC2_RX2DC_RANGE_OFFSET !=     QUASAR_RX2DC_RANGE_OFFSET)
#error QUASAR_DCOC2_RX2DC_RANGE_OFFSET not matching
#endif


#if ((QUASAR_DCOC2_RX2DCI_MASK >> QUASAR_DCOC2_RX2DCI_OFFSET) !=    QUASAR_RX2DCI_MASK  )
#error QUASAR_DCOC2_RX2DCI_MASK not matching
#endif
#if (QUASAR_DCOC2_RX2DCI_OFFSET !=  QUASAR_RX2DCI_OFFSET)
#error QUASAR_DCOC2_RX2DCI_OFFSET not matching
#endif


#if ((QUASAR_DCOC2_RX2DCQ_MASK >> QUASAR_DCOC2_RX2DCQ_OFFSET) !=    QUASAR_RX2DCQ_MASK  )
#error QUASAR_DCOC2_RX2DCQ_MASK not matching
#endif
#if (QUASAR_DCOC2_RX2DCQ_OFFSET !=  QUASAR_RX2DCQ_OFFSET)
#error QUASAR_DCOC2_RX2DCQ_OFFSET not matching
#endif


#if ((QUASAR_CFG1_CLIP_EN_0_MASK >> QUASAR_CFG1_CLIP_EN_0_OFFSET) !=    QUASAR_CLIP_EN_0_MASK  )
#error QUASAR_CFG1_CLIP_EN_0_MASK not matching
#endif
#if (QUASAR_CFG1_CLIP_EN_0_OFFSET !=    QUASAR_CLIP_EN_0_OFFSET)
#error QUASAR_CFG1_CLIP_EN_0_OFFSET not matching
#endif


#if ((QUASAR_CFG1_CLIP_EN_1_MASK >> QUASAR_CFG1_CLIP_EN_1_OFFSET) !=    QUASAR_CLIP_EN_1_MASK  )
#error QUASAR_CFG1_CLIP_EN_1_MASK not matching
#endif
#if (QUASAR_CFG1_CLIP_EN_1_OFFSET !=    QUASAR_CLIP_EN_1_OFFSET)
#error QUASAR_CFG1_CLIP_EN_1_OFFSET not matching
#endif


#if ((QUASAR_CFG1_CLIP_EN_2_MASK >> QUASAR_CFG1_CLIP_EN_2_OFFSET) !=    QUASAR_CLIP_EN_2_MASK  )
#error QUASAR_CFG1_CLIP_EN_2_MASK not matching
#endif
#if (QUASAR_CFG1_CLIP_EN_2_OFFSET !=    QUASAR_CLIP_EN_2_OFFSET)
#error QUASAR_CFG1_CLIP_EN_2_OFFSET not matching
#endif


#if ((QUASAR_CFG1_MOD_INV_MASK >> QUASAR_CFG1_MOD_INV_OFFSET) !=    QUASAR_MOD_INV_MASK  )
#error QUASAR_CFG1_MOD_INV_MASK not matching
#endif
#if (QUASAR_CFG1_MOD_INV_OFFSET !=  QUASAR_MOD_INV_OFFSET)
#error QUASAR_CFG1_MOD_INV_OFFSET not matching
#endif


#if ((QUASAR_CFG1_TX_RFLO_MASK >> QUASAR_CFG1_TX_RFLO_OFFSET) !=    QUASAR_TX_RFLO_MASK  )
#error QUASAR_CFG1_TX_RFLO_MASK not matching
#endif
#if (QUASAR_CFG1_TX_RFLO_OFFSET !=  QUASAR_TX_RFLO_OFFSET)
#error QUASAR_CFG1_TX_RFLO_OFFSET not matching
#endif


#if ((QUASAR_CFG1_TX_IFLO_MASK >> QUASAR_CFG1_TX_IFLO_OFFSET) !=    QUASAR_TX_IFLO_MASK  )
#error QUASAR_CFG1_TX_IFLO_MASK not matching
#endif
#if (QUASAR_CFG1_TX_IFLO_OFFSET !=  QUASAR_TX_IFLO_OFFSET)
#error QUASAR_CFG1_TX_IFLO_OFFSET not matching
#endif


#if ((QUASAR_CFG1_XO_DRV_MASK >> QUASAR_CFG1_XO_DRV_OFFSET) !=  QUASAR_XO_DRV_MASK  )
#error QUASAR_CFG1_XO_DRV_MASK not matching
#endif
#if (QUASAR_CFG1_XO_DRV_OFFSET !=   QUASAR_XO_DRV_OFFSET)
#error QUASAR_CFG1_XO_DRV_OFFSET not matching
#endif


#if ((QUASAR_CFG1_XO_BYP_MASK >> QUASAR_CFG1_XO_BYP_OFFSET) !=  QUASAR_XO_BYP_MASK  )
#error QUASAR_CFG1_XO_BYP_MASK not matching
#endif
#if (QUASAR_CFG1_XO_BYP_OFFSET !=   QUASAR_XO_BYP_OFFSET)
#error QUASAR_CFG1_XO_BYP_OFFSET not matching
#endif


#if ((QUASAR_CFG1_XO_BUF_EN_MASK >> QUASAR_CFG1_XO_BUF_EN_OFFSET) !=    QUASAR_XO_BUF_EN_MASK  )
#error QUASAR_CFG1_XO_BUF_EN_MASK not matching
#endif
#if (QUASAR_CFG1_XO_BUF_EN_OFFSET !=    QUASAR_XO_BUF_EN_OFFSET)
#error QUASAR_CFG1_XO_BUF_EN_OFFSET not matching
#endif


#if ((QUASAR_CFG1_TOUT_MASK >> QUASAR_CFG1_TOUT_OFFSET) !=  QUASAR_TOUT_MASK  )
#error QUASAR_CFG1_TOUT_MASK not matching
#endif
#if (QUASAR_CFG1_TOUT_OFFSET !=     QUASAR_TOUT_OFFSET)
#error QUASAR_CFG1_TOUT_OFFSET not matching
#endif


#if ((QUASAR_CFG1_TEN_MASK >> QUASAR_CFG1_TEN_OFFSET) !=    QUASAR_TEN_MASK  )
#error QUASAR_CFG1_TEN_MASK not matching
#endif
#if (QUASAR_CFG1_TEN_OFFSET !=  QUASAR_TEN_OFFSET)
#error QUASAR_CFG1_TEN_OFFSET not matching
#endif


#if ((QUASAR_CFG2_RC_ATUNE_VAL_MASK >> QUASAR_CFG2_RC_ATUNE_VAL_OFFSET) !=  QUASAR_RC_ATUNE_VAL_MASK  )
#error QUASAR_CFG2_RC_ATUNE_VAL_MASK not matching
#endif
#if (QUASAR_CFG2_RC_ATUNE_VAL_OFFSET !=     QUASAR_RC_ATUNE_VAL_OFFSET)
#error QUASAR_CFG2_RC_ATUNE_VAL_OFFSET not matching
#endif


#if ((QUASAR_CFG2_RC_TUNE_EN_MASK >> QUASAR_CFG2_RC_TUNE_EN_OFFSET) !=  QUASAR_RC_TUNE_EN_MASK  )
#error QUASAR_CFG2_RC_TUNE_EN_MASK not matching
#endif
#if (QUASAR_CFG2_RC_TUNE_EN_OFFSET !=   QUASAR_RC_TUNE_EN_OFFSET)
#error QUASAR_CFG2_RC_TUNE_EN_OFFSET not matching
#endif


#if ((QUASAR_CFG2_BBF_RX_TUNE_MASK >> QUASAR_CFG2_BBF_RX_TUNE_OFFSET) !=    QUASAR_BBF_RX_TUNE_MASK  )
#error QUASAR_CFG2_BBF_RX_TUNE_MASK not matching
#endif
#if (QUASAR_CFG2_BBF_RX_TUNE_OFFSET !=  QUASAR_BBF_RX_TUNE_OFFSET)
#error QUASAR_CFG2_BBF_RX_TUNE_OFFSET not matching
#endif


#if ((QUASAR_CFG2_BBF_TX_TUNE_MASK >> QUASAR_CFG2_BBF_TX_TUNE_OFFSET) !=    QUASAR_BBF_TX_TUNE_MASK  )
#error QUASAR_CFG2_BBF_TX_TUNE_MASK not matching
#endif
#if (QUASAR_CFG2_BBF_TX_TUNE_OFFSET !=  QUASAR_BBF_TX_TUNE_OFFSET)
#error QUASAR_CFG2_BBF_TX_TUNE_OFFSET not matching
#endif


#if ((QUASAR_CFG2_BBF_ATUNE_EN_MASK >> QUASAR_CFG2_BBF_ATUNE_EN_OFFSET) !=  QUASAR_BBF_ATUNE_EN_MASK  )
#error QUASAR_CFG2_BBF_ATUNE_EN_MASK not matching
#endif
#if (QUASAR_CFG2_BBF_ATUNE_EN_OFFSET !=     QUASAR_BBF_ATUNE_EN_OFFSET)
#error QUASAR_CFG2_BBF_ATUNE_EN_OFFSET not matching
#endif


#if ((QUASAR_CFG3_RX2_DCOC_EN_MASK >> QUASAR_CFG3_RX2_DCOC_EN_OFFSET) !=    QUASAR_RX2_DCOC_EN_MASK  )
#error QUASAR_CFG3_RX2_DCOC_EN_MASK not matching
#endif
#if (QUASAR_CFG3_RX2_DCOC_EN_OFFSET !=  QUASAR_RX2_DCOC_EN_OFFSET)
#error QUASAR_CFG3_RX2_DCOC_EN_OFFSET not matching
#endif


#if ((QUASAR_CFG3_RX1_DCOC_EN_MASK >> QUASAR_CFG3_RX1_DCOC_EN_OFFSET) !=    QUASAR_RX1_DCOC_EN_MASK  )
#error QUASAR_CFG3_RX1_DCOC_EN_MASK not matching
#endif
#if (QUASAR_CFG3_RX1_DCOC_EN_OFFSET !=  QUASAR_RX1_DCOC_EN_OFFSET)
#error QUASAR_CFG3_RX1_DCOC_EN_OFFSET not matching
#endif


#if ((QUASAR_CFG3_RX0_DCOC_EN_MASK >> QUASAR_CFG3_RX0_DCOC_EN_OFFSET) !=    QUASAR_RX0_DCOC_EN_MASK  )
#error QUASAR_CFG3_RX0_DCOC_EN_MASK not matching
#endif
#if (QUASAR_CFG3_RX0_DCOC_EN_OFFSET !=  QUASAR_RX0_DCOC_EN_OFFSET)
#error QUASAR_CFG3_RX0_DCOC_EN_OFFSET not matching
#endif


#if ((QUASAR_CFG3_TX1_D_MASK >> QUASAR_CFG3_TX1_D_OFFSET) !=    QUASAR_TX1_D_MASK  )
#error QUASAR_CFG3_TX1_D_MASK not matching
#endif
#if (QUASAR_CFG3_TX1_D_OFFSET !=    QUASAR_TX1_D_OFFSET)
#error QUASAR_CFG3_TX1_D_OFFSET not matching
#endif


#if ((QUASAR_CFG3_TX1D_D_MASK >> QUASAR_CFG3_TX1D_D_OFFSET) !=  QUASAR_TX1D_D_MASK  )
#error QUASAR_CFG3_TX1D_D_MASK not matching
#endif
#if (QUASAR_CFG3_TX1D_D_OFFSET !=   QUASAR_TX1D_D_OFFSET)
#error QUASAR_CFG3_TX1D_D_OFFSET not matching
#endif


#if ((QUASAR_CFG3_RX1_D_MASK >> QUASAR_CFG3_RX1_D_OFFSET) !=    QUASAR_RX1_D_MASK  )
#error QUASAR_CFG3_RX1_D_MASK not matching
#endif
#if (QUASAR_CFG3_RX1_D_OFFSET !=    QUASAR_RX1_D_OFFSET)
#error QUASAR_CFG3_RX1_D_OFFSET not matching
#endif


#if ((QUASAR_CFG4_CLK_GATE_MASK >> QUASAR_CFG4_CLK_GATE_OFFSET) !=  QUASAR_CLK_GATE_MASK  )
#error QUASAR_CFG4_CLK_GATE_MASK not matching
#endif
#if (QUASAR_CFG4_CLK_GATE_OFFSET !=     QUASAR_CLK_GATE_OFFSET)
#error QUASAR_CFG4_CLK_GATE_OFFSET not matching
#endif


#if ((QUASAR_CFG4_TX_DBIAS_MASK >> QUASAR_CFG4_TX_DBIAS_OFFSET) !=  QUASAR_TX_DBIAS_MASK  )
#error QUASAR_CFG4_TX_DBIAS_MASK not matching
#endif
#if (QUASAR_CFG4_TX_DBIAS_OFFSET !=     QUASAR_TX_DBIAS_OFFSET)
#error QUASAR_CFG4_TX_DBIAS_OFFSET not matching
#endif


#if ((QUASAR_CFG4_TX0_D_MASK >> QUASAR_CFG4_TX0_D_OFFSET) !=    QUASAR_TX0_D_MASK  )
#error QUASAR_CFG4_TX0_D_MASK not matching
#endif
#if (QUASAR_CFG4_TX0_D_OFFSET !=    QUASAR_TX0_D_OFFSET)
#error QUASAR_CFG4_TX0_D_OFFSET not matching
#endif


#if ((QUASAR_CFG4_TX0D_D_MASK >> QUASAR_CFG4_TX0D_D_OFFSET) !=  QUASAR_TX0D_D_MASK  )
#error QUASAR_CFG4_TX0D_D_MASK not matching
#endif
#if (QUASAR_CFG4_TX0D_D_OFFSET !=   QUASAR_TX0D_D_OFFSET)
#error QUASAR_CFG4_TX0D_D_OFFSET not matching
#endif


#if ((QUASAR_CFG4_RX0_D_MASK >> QUASAR_CFG4_RX0_D_OFFSET) !=    QUASAR_RX0_D_MASK  )
#error QUASAR_CFG4_RX0_D_MASK not matching
#endif
#if (QUASAR_CFG4_RX0_D_OFFSET !=    QUASAR_RX0_D_OFFSET)
#error QUASAR_CFG4_RX0_D_OFFSET not matching
#endif


#if ((QUASAR_CFG5_RX_IBIAS_EN_MASK >> QUASAR_CFG5_RX_IBIAS_EN_OFFSET) !=    QUASAR_RX_IBIAS_EN_MASK  )
#error QUASAR_CFG5_RX_IBIAS_EN_MASK not matching
#endif
#if (QUASAR_CFG5_RX_IBIAS_EN_OFFSET !=  QUASAR_RX_IBIAS_EN_OFFSET)
#error QUASAR_CFG5_RX_IBIAS_EN_OFFSET not matching
#endif


#if ((QUASAR_CFG5_RX_RF_MIX_EN_MASK >> QUASAR_CFG5_RX_RF_MIX_EN_OFFSET) !=  QUASAR_RX_RF_MIX_EN_MASK  )
#error QUASAR_CFG5_RX_RF_MIX_EN_MASK not matching
#endif
#if (QUASAR_CFG5_RX_RF_MIX_EN_OFFSET !=     QUASAR_RX_RF_MIX_EN_OFFSET)
#error QUASAR_CFG5_RX_RF_MIX_EN_OFFSET not matching
#endif


#if ((QUASAR_CFG5_RX_IF_MIX_EN_MASK >> QUASAR_CFG5_RX_IF_MIX_EN_OFFSET) !=  QUASAR_RX_IF_MIX_EN_MASK  )
#error QUASAR_CFG5_RX_IF_MIX_EN_MASK not matching
#endif
#if (QUASAR_CFG5_RX_IF_MIX_EN_OFFSET !=     QUASAR_RX_IF_MIX_EN_OFFSET)
#error QUASAR_CFG5_RX_IF_MIX_EN_OFFSET not matching
#endif


#if ((QUASAR_CFG5_RX_IF_TUN_MASK >> QUASAR_CFG5_RX_IF_TUN_OFFSET) !=    QUASAR_RX_IF_TUN_MASK  )
#error QUASAR_CFG5_RX_IF_TUN_MASK not matching
#endif
#if (QUASAR_CFG5_RX_IF_TUN_OFFSET !=    QUASAR_RX_IF_TUN_OFFSET)
#error QUASAR_CFG5_RX_IF_TUN_OFFSET not matching
#endif


#if ((QUASAR_CFG5_TX_RF_TUN_MASK >> QUASAR_CFG5_TX_RF_TUN_OFFSET) !=    QUASAR_TX_RF_TUN_MASK  )
#error QUASAR_CFG5_TX_RF_TUN_MASK not matching
#endif
#if (QUASAR_CFG5_TX_RF_TUN_OFFSET !=    QUASAR_TX_RF_TUN_OFFSET)
#error QUASAR_CFG5_TX_RF_TUN_OFFSET not matching
#endif


#if ((QUASAR_CFG5_TX_IF_TUN_MASK >> QUASAR_CFG5_TX_IF_TUN_OFFSET) !=    QUASAR_TX_IF_TUN_MASK  )
#error QUASAR_CFG5_TX_IF_TUN_MASK not matching
#endif
#if (QUASAR_CFG5_TX_IF_TUN_OFFSET !=    QUASAR_TX_IF_TUN_OFFSET)
#error QUASAR_CFG5_TX_IF_TUN_OFFSET not matching
#endif


#if ((QUASAR_CFG5_RX2_D_MASK >> QUASAR_CFG5_RX2_D_OFFSET) !=    QUASAR_RX2_D_MASK  )
#error QUASAR_CFG5_RX2_D_MASK not matching
#endif
#if (QUASAR_CFG5_RX2_D_OFFSET !=    QUASAR_RX2_D_OFFSET)
#error QUASAR_CFG5_RX2_D_OFFSET not matching
#endif


#if ((QUASAR_CFG6_RX_CASC_GC_MASK >> QUASAR_CFG6_RX_CASC_GC_OFFSET) !=  QUASAR_RX_CASC_GC_MASK  )
#error QUASAR_CFG6_RX_CASC_GC_MASK not matching
#endif
#if (QUASAR_CFG6_RX_CASC_GC_OFFSET !=   QUASAR_RX_CASC_GC_OFFSET)
#error QUASAR_CFG6_RX_CASC_GC_OFFSET not matching
#endif


#if ((QUASAR_CFG6_TX_CASC_GC_MASK >> QUASAR_CFG6_TX_CASC_GC_OFFSET) !=  QUASAR_TX_CASC_GC_MASK  )
#error QUASAR_CFG6_TX_CASC_GC_MASK not matching
#endif
#if (QUASAR_CFG6_TX_CASC_GC_OFFSET !=   QUASAR_TX_CASC_GC_OFFSET)
#error QUASAR_CFG6_TX_CASC_GC_OFFSET not matching
#endif


#if ((QUASAR_CFG6_RX_IF_LODRV_EN_MASK >> QUASAR_CFG6_RX_IF_LODRV_EN_OFFSET) !=  QUASAR_RX_IF_LODRV_EN_MASK  )
#error QUASAR_CFG6_RX_IF_LODRV_EN_MASK not matching
#endif
#if (QUASAR_CFG6_RX_IF_LODRV_EN_OFFSET !=   QUASAR_RX_IF_LODRV_EN_OFFSET)
#error QUASAR_CFG6_RX_IF_LODRV_EN_OFFSET not matching
#endif


#if ((QUASAR_CFG6_XO_GM_MASK >> QUASAR_CFG6_XO_GM_OFFSET) !=    QUASAR_XO_GM_MASK  )
#error QUASAR_CFG6_XO_GM_MASK not matching
#endif
#if (QUASAR_CFG6_XO_GM_OFFSET !=    QUASAR_XO_GM_OFFSET)
#error QUASAR_CFG6_XO_GM_OFFSET not matching
#endif


#if ((QUASAR_CFG6_CLIP_TEST_MASK >> QUASAR_CFG6_CLIP_TEST_OFFSET) !=    QUASAR_CLIP_TEST_MASK  )
#error QUASAR_CFG6_CLIP_TEST_MASK not matching
#endif
#if (QUASAR_CFG6_CLIP_TEST_OFFSET !=    QUASAR_CLIP_TEST_OFFSET)
#error QUASAR_CFG6_CLIP_TEST_OFFSET not matching
#endif


#if ((QUASAR_CFG6_CLIP_FREQ_MASK >> QUASAR_CFG6_CLIP_FREQ_OFFSET) !=    QUASAR_CLIP_FREQ_MASK  )
#error QUASAR_CFG6_CLIP_FREQ_MASK not matching
#endif
#if (QUASAR_CFG6_CLIP_FREQ_OFFSET !=    QUASAR_CLIP_FREQ_OFFSET)
#error QUASAR_CFG6_CLIP_FREQ_OFFSET not matching
#endif


#if ((QUASAR_CFG6_CLIP_DET_TH_MASK >> QUASAR_CFG6_CLIP_DET_TH_OFFSET) !=    QUASAR_CLIP_DET_TH_MASK  )
#error QUASAR_CFG6_CLIP_DET_TH_MASK not matching
#endif
#if (QUASAR_CFG6_CLIP_DET_TH_OFFSET !=  QUASAR_CLIP_DET_TH_OFFSET)
#error QUASAR_CFG6_CLIP_DET_TH_OFFSET not matching
#endif


#if ((QUASAR_CFG6_BBF_BIAS_MODE_MASK >> QUASAR_CFG6_BBF_BIAS_MODE_OFFSET) !=    QUASAR_BBF_BIAS_MODE_MASK  )
#error QUASAR_CFG6_BBF_BIAS_MODE_MASK not matching
#endif
#if (QUASAR_CFG6_BBF_BIAS_MODE_OFFSET !=    QUASAR_BBF_BIAS_MODE_OFFSET)
#error QUASAR_CFG6_BBF_BIAS_MODE_OFFSET not matching
#endif


#if ((QUASAR_CFG6_TX_REG_MODE_MASK >> QUASAR_CFG6_TX_REG_MODE_OFFSET) !=    QUASAR_TX_REG_MODE_MASK  )
#error QUASAR_CFG6_TX_REG_MODE_MASK not matching
#endif
#if (QUASAR_CFG6_TX_REG_MODE_OFFSET !=  QUASAR_TX_REG_MODE_OFFSET)
#error QUASAR_CFG6_TX_REG_MODE_OFFSET not matching
#endif


#if ((QUASAR_CFG6_TX_VREG_BYP_MASK >> QUASAR_CFG6_TX_VREG_BYP_OFFSET) !=    QUASAR_TX_VREG_BYP_MASK  )
#error QUASAR_CFG6_TX_VREG_BYP_MASK not matching
#endif
#if (QUASAR_CFG6_TX_VREG_BYP_OFFSET !=  QUASAR_TX_VREG_BYP_OFFSET)
#error QUASAR_CFG6_TX_VREG_BYP_OFFSET not matching
#endif


#if ((QUASAR_TEST1_NDIV_OUT_MASK >> QUASAR_TEST1_NDIV_OUT_OFFSET) !=    QUASAR_NDIV_OUT_MASK  )
#error QUASAR_TEST1_NDIV_OUT_MASK not matching
#endif
#if (QUASAR_TEST1_NDIV_OUT_OFFSET !=    QUASAR_NDIV_OUT_OFFSET)
#error QUASAR_TEST1_NDIV_OUT_OFFSET not matching
#endif


#if ((QUASAR_TEST1_RX_LB_GAIN_MASK >> QUASAR_TEST1_RX_LB_GAIN_OFFSET) !=    QUASAR_RX_LB_GAIN_MASK  )
#error QUASAR_TEST1_RX_LB_GAIN_MASK not matching
#endif
#if (QUASAR_TEST1_RX_LB_GAIN_OFFSET !=  QUASAR_RX_LB_GAIN_OFFSET)
#error QUASAR_TEST1_RX_LB_GAIN_OFFSET not matching
#endif


#if ((QUASAR_TEST1_TX_LB_GAIN_MASK >> QUASAR_TEST1_TX_LB_GAIN_OFFSET) !=    QUASAR_TX_LB_GAIN_MASK  )
#error QUASAR_TEST1_TX_LB_GAIN_MASK not matching
#endif
#if (QUASAR_TEST1_TX_LB_GAIN_OFFSET !=  QUASAR_TX_LB_GAIN_OFFSET)
#error QUASAR_TEST1_TX_LB_GAIN_OFFSET not matching
#endif


#if ((QUASAR_TEST1_TEST_LB_RF_MASK >> QUASAR_TEST1_TEST_LB_RF_OFFSET) !=    QUASAR_TEST_LB_RF_MASK  )
#error QUASAR_TEST1_TEST_LB_RF_MASK not matching
#endif
#if (QUASAR_TEST1_TEST_LB_RF_OFFSET !=  QUASAR_TEST_LB_RF_OFFSET)
#error QUASAR_TEST1_TEST_LB_RF_OFFSET not matching
#endif


#if ((QUASAR_TEST1_RX_IQ_TEST_0_MASK >> QUASAR_TEST1_RX_IQ_TEST_0_OFFSET) !=    QUASAR_RX_IQ_TEST_0_MASK  )
#error QUASAR_TEST1_RX_IQ_TEST_0_MASK not matching
#endif
#if (QUASAR_TEST1_RX_IQ_TEST_0_OFFSET !=    QUASAR_RX_IQ_TEST_0_OFFSET)
#error QUASAR_TEST1_RX_IQ_TEST_0_OFFSET not matching
#endif


#if ((QUASAR_TEST1_RX_IQ_TEST_1_MASK >> QUASAR_TEST1_RX_IQ_TEST_1_OFFSET) !=    QUASAR_RX_IQ_TEST_1_MASK  )
#error QUASAR_TEST1_RX_IQ_TEST_1_MASK not matching
#endif
#if (QUASAR_TEST1_RX_IQ_TEST_1_OFFSET !=    QUASAR_RX_IQ_TEST_1_OFFSET)
#error QUASAR_TEST1_RX_IQ_TEST_1_OFFSET not matching
#endif


#if ((QUASAR_TEST1_RX_IQ_TEST_2_1_MASK >> QUASAR_TEST1_RX_IQ_TEST_2_1_OFFSET) !=    QUASAR_RX_IQ_TEST_2_1_MASK  )
#error QUASAR_TEST1_RX_IQ_TEST_2_1_MASK not matching
#endif
#if (QUASAR_TEST1_RX_IQ_TEST_2_1_OFFSET !=  QUASAR_RX_IQ_TEST_2_1_OFFSET)
#error QUASAR_TEST1_RX_IQ_TEST_2_1_OFFSET not matching
#endif


#if ((QUASAR_TEST1_RX_IQ_TEST_2_0_MASK >> QUASAR_TEST1_RX_IQ_TEST_2_0_OFFSET) !=    QUASAR_RX_IQ_TEST_2_0_MASK  )
#error QUASAR_TEST1_RX_IQ_TEST_2_0_MASK not matching
#endif
#if (QUASAR_TEST1_RX_IQ_TEST_2_0_OFFSET !=  QUASAR_RX_IQ_TEST_2_0_OFFSET)
#error QUASAR_TEST1_RX_IQ_TEST_2_0_OFFSET not matching
#endif


#if ((QUASAR_TEST1_TX_CAL_EN_0_MASK >> QUASAR_TEST1_TX_CAL_EN_0_OFFSET) !=  QUASAR_TX_CAL_EN_0_MASK  )
#error QUASAR_TEST1_TX_CAL_EN_0_MASK not matching
#endif
#if (QUASAR_TEST1_TX_CAL_EN_0_OFFSET !=     QUASAR_TX_CAL_EN_0_OFFSET)
#error QUASAR_TEST1_TX_CAL_EN_0_OFFSET not matching
#endif


#if ((QUASAR_TEST1_TX_CAL_EN_1_MASK >> QUASAR_TEST1_TX_CAL_EN_1_OFFSET) !=  QUASAR_TX_CAL_EN_1_MASK  )
#error QUASAR_TEST1_TX_CAL_EN_1_MASK not matching
#endif
#if (QUASAR_TEST1_TX_CAL_EN_1_OFFSET !=     QUASAR_TX_CAL_EN_1_OFFSET)
#error QUASAR_TEST1_TX_CAL_EN_1_OFFSET not matching
#endif


#if ((QUASAR_TEST1_DET_OFFSET_MASK >> QUASAR_TEST1_DET_OFFSET_OFFSET) !=    QUASAR_DET_OFFSET_MASK  )
#error QUASAR_TEST1_DET_MASK_MASK not matching
#endif
#if (QUASAR_TEST1_DET_OFFSET_OFFSET !=  QUASAR_DET_OFFSET_OFFSET)
#error QUASAR_TEST1_DET_MASK_OFFSET not matching
#endif


#if ((QUASAR_TEST1_DET_GAIN_MASK >> QUASAR_TEST1_DET_GAIN_OFFSET) !=    QUASAR_DET_GAIN_MASK  )
#error QUASAR_TEST1_DET_GAIN_MASK not matching
#endif
#if (QUASAR_TEST1_DET_GAIN_OFFSET !=    QUASAR_DET_GAIN_OFFSET)
#error QUASAR_TEST1_DET_GAIN_OFFSET not matching
#endif


#if ((QUASAR_TEST1_RDIV_TEST_MASK >> QUASAR_TEST1_RDIV_TEST_OFFSET) !=  QUASAR_RDIV_TEST_MASK  )
#error QUASAR_TEST1_RDIV_TEST_MASK not matching
#endif
#if (QUASAR_TEST1_RDIV_TEST_OFFSET !=   QUASAR_RDIV_TEST_OFFSET)
#error QUASAR_TEST1_RDIV_TEST_OFFSET not matching
#endif


#if ((QUASAR_TEST2_TX_DRVR_GAIN_MASK >> QUASAR_TEST2_TX_DRVR_GAIN_OFFSET) !=    QUASAR_TX_DRVR_GAIN_MASK  )
#error QUASAR_TEST2_TX_DRVR_GAIN_MASK not matching
#endif
#if (QUASAR_TEST2_TX_DRVR_GAIN_OFFSET !=    QUASAR_TX_DRVR_GAIN_OFFSET)
#error QUASAR_TEST2_TX_DRVR_GAIN_OFFSET not matching
#endif


#if ((QUASAR_TEST2_TX_VGA_GAIN_MASK >> QUASAR_TEST2_TX_VGA_GAIN_OFFSET) !=  QUASAR_TX_VGA_GAIN_MASK  )
#error QUASAR_TEST2_TX_VGA_GAIN_MASK not matching
#endif
#if (QUASAR_TEST2_TX_VGA_GAIN_OFFSET !=     QUASAR_TX_VGA_GAIN_OFFSET)
#error QUASAR_TEST2_TX_VGA_GAIN_OFFSET not matching
#endif


#if ((QUASAR_TEST2_TX_IQ_GAIN_MASK >> QUASAR_TEST2_TX_IQ_GAIN_OFFSET) !=    QUASAR_TX_IQ_GAIN_MASK  )
#error QUASAR_TEST2_TX_IQ_GAIN_MASK not matching
#endif
#if (QUASAR_TEST2_TX_IQ_GAIN_OFFSET !=  QUASAR_TX_IQ_GAIN_OFFSET)
#error QUASAR_TEST2_TX_IQ_GAIN_OFFSET not matching
#endif


#if ((QUASAR_TEST2_TX_GTEST_MASK >> QUASAR_TEST2_TX_GTEST_OFFSET) !=    QUASAR_TX_GTEST_MASK  )
#error QUASAR_TEST2_TX_GTEST_MASK not matching
#endif
#if (QUASAR_TEST2_TX_GTEST_OFFSET !=    QUASAR_TX_GTEST_OFFSET)
#error QUASAR_TEST2_TX_GTEST_OFFSET not matching
#endif


#if ((QUASAR_TEST2_BBF_IBIAS_CTL_MASK >> QUASAR_TEST2_BBF_IBIAS_CTL_OFFSET) !=  QUASAR_BBF_IBIAS_CTL_MASK  )
#error QUASAR_TEST2_BBF_IBIAS_CTL_MASK not matching
#endif
#if (QUASAR_TEST2_BBF_IBIAS_CTL_OFFSET !=   QUASAR_BBF_IBIAS_CTL_OFFSET)
#error QUASAR_TEST2_BBF_IBIAS_CTL_OFFSET not matching
#endif


#if ((QUASAR_TEST3_BBF_TEST_I_MASK >> QUASAR_TEST3_BBF_TEST_I_OFFSET) !=    QUASAR_BBF_TEST_I_MASK  )
#error QUASAR_TEST3_BBF_TEST_I_MASK not matching
#endif
#if (QUASAR_TEST3_BBF_TEST_I_OFFSET !=  QUASAR_BBF_TEST_I_OFFSET)
#error QUASAR_TEST3_BBF_TEST_I_OFFSET not matching
#endif


#if ((QUASAR_TEST3_BBF_TEST_Q_MASK >> QUASAR_TEST3_BBF_TEST_Q_OFFSET) !=    QUASAR_BBF_TEST_Q_MASK  )
#error QUASAR_TEST3_BBF_TEST_Q_MASK not matching
#endif
#if (QUASAR_TEST3_BBF_TEST_Q_OFFSET !=  QUASAR_BBF_TEST_Q_OFFSET)
#error QUASAR_TEST3_BBF_TEST_Q_OFFSET not matching
#endif


#if ((QUASAR_TEST3_CT_VAL_AUTO_MASK >> QUASAR_TEST3_CT_VAL_AUTO_OFFSET) !=  QUASAR_CT_VAL_AUTO_MASK  )
#error QUASAR_TEST3_CT_VAL_AUTO_MASK not matching
#endif
#if (QUASAR_TEST3_CT_VAL_AUTO_OFFSET !=     QUASAR_CT_VAL_AUTO_OFFSET)
#error QUASAR_TEST3_CT_VAL_AUTO_OFFSET not matching
#endif


#if ((QUASAR_TEST4_IO_TEST_MASK >> QUASAR_TEST4_IO_TEST_OFFSET) !=  QUASAR_IO_TEST_MASK  )
#error QUASAR_TEST4_IO_TEST_MASK not matching
#endif
#if (QUASAR_TEST4_IO_TEST_OFFSET !=     QUASAR_IO_TEST_OFFSET)
#error QUASAR_TEST4_IO_TEST_OFFSET not matching
#endif


#if ((QUASAR_TEST4_TX_RF_EN_MASK >> QUASAR_TEST4_TX_RF_EN_OFFSET) !=    QUASAR_TX_RF_EN_MASK  )
#error QUASAR_TEST4_TX_RF_EN_MASK not matching
#endif
#if (QUASAR_TEST4_TX_RF_EN_OFFSET !=    QUASAR_TX_RF_EN_OFFSET)
#error QUASAR_TEST4_TX_RF_EN_OFFSET not matching
#endif


#if ((QUASAR_TEST4_TX_DRVR_EN_MASK >> QUASAR_TEST4_TX_DRVR_EN_OFFSET) !=    QUASAR_TX_DRVR_EN_MASK  )
#error QUASAR_TEST4_TX_DRVR_EN_MASK not matching
#endif
#if (QUASAR_TEST4_TX_DRVR_EN_OFFSET !=  QUASAR_TX_DRVR_EN_OFFSET)
#error QUASAR_TEST4_TX_DRVR_EN_OFFSET not matching
#endif


#if ((QUASAR_TEST4_TX_IQ_EN_MASK >> QUASAR_TEST4_TX_IQ_EN_OFFSET) !=    QUASAR_TX_IQ_EN_MASK  )
#error QUASAR_TEST4_TX_IQ_EN_MASK not matching
#endif
#if (QUASAR_TEST4_TX_IQ_EN_OFFSET !=    QUASAR_TX_IQ_EN_OFFSET)
#error QUASAR_TEST4_TX_IQ_EN_OFFSET not matching
#endif


#if ((QUASAR_TEST4_BBF_ENQ_MASK >> QUASAR_TEST4_BBF_ENQ_OFFSET) !=  QUASAR_BBF_ENQ_MASK  )
#error QUASAR_TEST4_BBF_ENQ_MASK not matching
#endif
#if (QUASAR_TEST4_BBF_ENQ_OFFSET !=     QUASAR_BBF_ENQ_OFFSET)
#error QUASAR_TEST4_BBF_ENQ_OFFSET not matching
#endif


#if ((QUASAR_TEST4_BBF_ENI_MASK >> QUASAR_TEST4_BBF_ENI_OFFSET) !=  QUASAR_BBF_ENI_MASK  )
#error QUASAR_TEST4_BBF_ENI_MASK not matching
#endif
#if (QUASAR_TEST4_BBF_ENI_OFFSET !=     QUASAR_BBF_ENI_OFFSET)
#error QUASAR_TEST4_BBF_ENI_OFFSET not matching
#endif


#if ((QUASAR_TEST5_RX_GMTUNE_EN_MASK >> QUASAR_TEST5_RX_GMTUNE_EN_OFFSET) !=    QUASAR_RX_GMTUNE_EN_MASK  )
#error QUASAR_TEST5_RX_GMTUNE_EN_MASK not matching
#endif
#if (QUASAR_TEST5_RX_GMTUNE_EN_OFFSET !=    QUASAR_RX_GMTUNE_EN_OFFSET)
#error QUASAR_TEST5_RX_GMTUNE_EN_OFFSET not matching
#endif


#if ((QUASAR_TEST5_XO_REG_BYP_MASK >> QUASAR_TEST5_XO_REG_BYP_OFFSET) !=    QUASAR_XO_REG_BYP_MASK  )
#error QUASAR_TEST5_XO_REG_BYP_MASK not matching
#endif
#if (QUASAR_TEST5_XO_REG_BYP_OFFSET !=  QUASAR_XO_REG_BYP_OFFSET)
#error QUASAR_TEST5_XO_REG_BYP_OFFSET not matching
#endif


#if ((QUASAR_TEST5_XO_PLL_BUF_EN_MASK >> QUASAR_TEST5_XO_PLL_BUF_EN_OFFSET) !=  QUASAR_XO_PLL_BUF_EN_MASK  )
#error QUASAR_TEST5_XO_PLL_BUF_EN_MASK not matching
#endif
#if (QUASAR_TEST5_XO_PLL_BUF_EN_OFFSET !=   QUASAR_XO_PLL_BUF_EN_OFFSET)
#error QUASAR_TEST5_XO_PLL_BUF_EN_OFFSET not matching
#endif


#if ((QUASAR_TEST5_ATEST_MASK >> QUASAR_TEST5_ATEST_OFFSET) !=  QUASAR_ATEST_MASK  )
#error QUASAR_TEST5_ATEST_MASK not matching
#endif
#if (QUASAR_TEST5_ATEST_OFFSET !=   QUASAR_ATEST_OFFSET)
#error QUASAR_TEST5_ATEST_OFFSET not matching
#endif


#if ((QUASAR_TEST5_ATEST_EN_MASK >> QUASAR_TEST5_ATEST_EN_OFFSET) !=    QUASAR_ATEST_EN_MASK  )
#error QUASAR_TEST5_ATEST_EN_MASK not matching
#endif
#if (QUASAR_TEST5_ATEST_EN_OFFSET !=    QUASAR_ATEST_EN_OFFSET)
#error QUASAR_TEST5_ATEST_EN_OFFSET not matching
#endif


#if ((QUASAR_TEST5_BBF_GAIN2_MASK >> QUASAR_TEST5_BBF_GAIN2_OFFSET) !=  QUASAR_BBF_GAIN2_MASK  )
#error QUASAR_TEST5_BBF_GAIN2_MASK not matching
#endif
#if (QUASAR_TEST5_BBF_GAIN2_OFFSET !=   QUASAR_BBF_GAIN2_OFFSET)
#error QUASAR_TEST5_BBF_GAIN2_OFFSET not matching
#endif


#if ((QUASAR_TEST5_BBF_GAIN1_MASK >> QUASAR_TEST5_BBF_GAIN1_OFFSET) !=  QUASAR_BBF_GAIN1_MASK  )
#error QUASAR_TEST5_BBF_GAIN1_MASK not matching
#endif
#if (QUASAR_TEST5_BBF_GAIN1_OFFSET !=   QUASAR_BBF_GAIN1_OFFSET)
#error QUASAR_TEST5_BBF_GAIN1_OFFSET not matching
#endif


#if ((QUASAR_TEST5_BBF_GAIN_TEST_MASK >> QUASAR_TEST5_BBF_GAIN_TEST_OFFSET) !=  QUASAR_BBF_GAIN_TEST_MASK  )
#error QUASAR_TEST5_BBF_GAIN_TEST_MASK not matching
#endif
#if (QUASAR_TEST5_BBF_GAIN_TEST_OFFSET !=   QUASAR_BBF_GAIN_TEST_OFFSET)
#error QUASAR_TEST5_BBF_GAIN_TEST_OFFSET not matching
#endif


#if ((QUASAR_TEST6_TX1_DCOC_EN_MASK >> QUASAR_TEST6_TX1_DCOC_EN_OFFSET) !=  QUASAR_TX1_DCOC_EN_MASK  )
#error QUASAR_TEST6_TX1_DCOC_EN_MASK not matching
#endif
#if (QUASAR_TEST6_TX1_DCOC_EN_OFFSET !=     QUASAR_TX1_DCOC_EN_OFFSET)
#error QUASAR_TEST6_TX1_DCOC_EN_OFFSET not matching
#endif


#if ((QUASAR_TEST6_TX0_DCOC_EN_MASK >> QUASAR_TEST6_TX0_DCOC_EN_OFFSET) !=  QUASAR_TX0_DCOC_EN_MASK  )
#error QUASAR_TEST6_TX0_DCOC_EN_MASK not matching
#endif
#if (QUASAR_TEST6_TX0_DCOC_EN_OFFSET !=     QUASAR_TX0_DCOC_EN_OFFSET)
#error QUASAR_TEST6_TX0_DCOC_EN_OFFSET not matching
#endif


#if ((QUASAR_TEST6_TX0_DCOC_I_MASK >> QUASAR_TEST6_TX0_DCOC_I_OFFSET) !=    QUASAR_TX0_DCOC_I_MASK  )
#error QUASAR_TEST6_TX0_DCOC_I_MASK not matching
#endif
#if (QUASAR_TEST6_TX0_DCOC_I_OFFSET !=  QUASAR_TX0_DCOC_I_OFFSET)
#error QUASAR_TEST6_TX0_DCOC_I_OFFSET not matching
#endif


#if ((QUASAR_TEST6_TX0_DCOC_Q_MASK >> QUASAR_TEST6_TX0_DCOC_Q_OFFSET) !=    QUASAR_TX0_DCOC_Q_MASK  )
#error QUASAR_TEST6_TX0_DCOC_Q_MASK not matching
#endif
#if (QUASAR_TEST6_TX0_DCOC_Q_OFFSET !=  QUASAR_TX0_DCOC_Q_OFFSET)
#error QUASAR_TEST6_TX0_DCOC_Q_OFFSET not matching
#endif


#if ((QUASAR_TEST6_ADC_TEST_MASK >> QUASAR_TEST6_ADC_TEST_OFFSET) !=    QUASAR_ADC_TEST_MASK  )
#error QUASAR_TEST6_ADC_TEST_MASK not matching
#endif
#if (QUASAR_TEST6_ADC_TEST_OFFSET !=    QUASAR_ADC_TEST_OFFSET)
#error QUASAR_TEST6_ADC_TEST_OFFSET not matching
#endif


#if ((QUASAR_TEST6_ADC_TEST_EN_MASK >> QUASAR_TEST6_ADC_TEST_EN_OFFSET) !=  QUASAR_ADC_TEST_EN_MASK  )
#error QUASAR_TEST6_ADC_TEST_EN_MASK not matching
#endif
#if (QUASAR_TEST6_ADC_TEST_EN_OFFSET !=     QUASAR_ADC_TEST_EN_OFFSET)
#error QUASAR_TEST6_ADC_TEST_EN_OFFSET not matching
#endif


#if ((QUASAR_SPARES_RX_MAINT_MASK >> QUASAR_SPARES_RX_MAINT_OFFSET) !=  QUASAR_RX_MAINT_MASK  )
#error QUASAR_SPARES_RX_MAINT_MASK not matching
#endif
#if (QUASAR_SPARES_RX_MAINT_OFFSET !=   QUASAR_RX_MAINT_OFFSET)
#error QUASAR_SPARES_RX_MAINT_OFFSET not matching
#endif


#if ((QUASAR_SPARES_SPARES_MASK >> QUASAR_SPARES_SPARES_OFFSET) !=  QUASAR_SPARES_MASK  )
#error QUASAR_SPARES_SPARES_MASK not matching
#endif
#if (QUASAR_SPARES_SPARES_OFFSET !=     QUASAR_SPARES_OFFSET)
#error QUASAR_SPARES_SPARES_OFFSET not matching
#endif


#if ((QUASAR_SPARES_TX1_DCOC_I_MASK >> QUASAR_SPARES_TX1_DCOC_I_OFFSET) !=  QUASAR_TX1_DCOC_I_MASK  )
#error QUASAR_SPARES_TX1_DCOC_I_MASK not matching
#endif
#if (QUASAR_SPARES_TX1_DCOC_I_OFFSET !=     QUASAR_TX1_DCOC_I_OFFSET)
#error QUASAR_SPARES_TX1_DCOC_I_OFFSET not matching
#endif


#if ((QUASAR_SPARES_TX1_DCOC_Q_MASK >> QUASAR_SPARES_TX1_DCOC_Q_OFFSET) !=  QUASAR_TX1_DCOC_Q_MASK  )
#error QUASAR_SPARES_TX1_DCOC_Q_MASK not matching
#endif
#if (QUASAR_SPARES_TX1_DCOC_Q_OFFSET !=     QUASAR_TX1_DCOC_Q_OFFSET)
#error QUASAR_SPARES_TX1_DCOC_Q_OFFSET not matching
#endif


#if ((QUASAR_RESET_RESET_MASK >> QUASAR_RESET_RESET_OFFSET) !=  QUASAR_RESET_MASK  )
#error QUASAR_RESET_RESET_MASK not matching
#endif
#if (QUASAR_RESET_RESET_OFFSET !=   QUASAR_RESET_OFFSET)
#error QUASAR_RESET_RESET_OFFSET not matching
#endif


#if ((QUASAR_SPARE2_SPARES2_MASK >> QUASAR_SPARE2_SPARES2_OFFSET) !=    QUASAR_SPARES2_MASK  )
#error QUASAR_SPARE2_SPARES2_MASK not matching
#endif
#if (QUASAR_SPARE2_SPARES2_OFFSET !=    QUASAR_SPARES2_OFFSET)
#error QUASAR_SPARE2_SPARES2_OFFSET not matching
#endif




#endif
